apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: sistema-gaturro-public-subnet-c
spec:
  forProvider:
    mapPublicIpOnLaunch: true
    availabilityZone: us-west-1b
    cidrBlock: 10.0.32.0/19
    region: us-west-1
    vpcIdRef: 
      name: sistema-gaturro-vpc
    tags:
      Name: sistema-gaturro-public-subnet-c
  providerConfigRef:
    name: aws
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: sistema-gaturro-rta-public-c
spec:
  forProvider:
    region: us-west-1
    subnetIdRef:
      name: sistema-gaturro-public-subnet-c
    routeTableIdRef:
      name: sistema-gaturro-route-table-public
    tags:
      Name: sistema-gaturro-rta-public-c
  providerConfigRef:
    name: aws