environment: prod

deployment:
  image:  
    tag: 3
  replicas: 1
  labels:
    full-name: piaggio-frontend-prod

configmap: 
  nginxConf: |-
      location /api {
          proxy_pass http://piaggio-backend-prod-service:3000/;
      }
