environment: stage

deployment:
  image:  
    tag: 
  replicas: 1
  labels:
    full-name: piaggio-frontend-stage

configmap: 
  nginxConf: |-
      location /api {
          proxy_pass http://piaggio-backend-stage-service:3000/;
      }
