environment: dev
    
deployment:
  image:  
    tag: 3
  replicas: 1
  labels:
    full-name: piaggio-frontend-dev

configmap: 
  nginxConf: |-
      location /api {
          proxy_pass http://piaggio-backend-dev-service:3000/;
      }
