apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    roleNameSelector:
      matchControllerRef: true
      matchLabels:
        role: managed-nodegroup