apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: AmazonSSMManagedInstanceCore-policy-attachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    # policyArnSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: role
    roleRef:
      name: sistema-gaturro-eks-role
    # roleSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: role