apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    roleNameSelector:
      matchControllerRef: true
      matchLabels:
        role:  managed-nodegroup
