apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: AmazonEC2ContainerRegistryReadOnly-policy-attachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    # policyArnSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: role
    roleRef:
      name: sistema-gaturro-eks-ng-role
    # roleSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: role
  providerConfigRef:
    name: aws