apiVersion: ec2.aws.upbound.io/v1beta1
kind: DefaultSubnet
metadata:
  name: sistema-gaturro-subnet
spec:
  forProvider:
    availabilityZone: us-west-1a
    region: us-west-1
    tags:
      Name: sistema-gaturro-subnet
  providerConfigRef:
    name: aws