apiVersion: ec2.aws.upbound.io/v1beta1
kind: DefaultVPC
metadata:
  name: sistema-gaturro-vpc
spec:
  forProvider:
    region: us-west-1
    tags:
      Name: sistema-gaturro-vpc
  providerConfigRef:
    name: aws