apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.system }}-${{ values.service }}-eks-cluster
  description: ${{ values.service }} eks cluster for the ${{ values.system }} system
  tags:
    - aws 
    - eks
spec:
  type: kubernetes-cluster
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
