apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-eks-cluster
  title: Deploy New EKS Cluster
  description: Creates all the neccesary resources in AWS for deploying an EKS cluster.
  tags:
    - aws
    - eks
spec:
  owner: web@example.com
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - system
        - service
        - region
        - description
        - owner
      properties:
        # system:
          # title: System
          # type: string
          # description: Name of the system the new EKS cluster belongs to. Example -> 'my-app'
          # ui:field: EntityNamePicker
          # ui:autofocus: true

        # system:
        #   title: System
        #   type: string
        #   description: System the new EKS cluster belongs to.
        #   ui:field: EntityPicker
        #   ui:options:
        #     catalogFilter:
        #       kind: System
        #     defaultKind: System

        system:
          title: System
          type: string
          description: System the new EKS cluster belongs to.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: System

        service:
          title: Name
          type: string
          description: Unique name of the new EKS cluster.
          ui:field: EntityNamePicker
        region:
          title: Region
          type: string
          description: In what AWS region will the EKS cluster be deployed.
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this service is for
        owner:
          title: Owner
          type: string
          description: Owner of the service
          ui:field: OwnerPicker
          ui:options:
            # allowedKinds: # DEPRACATED
            #   - Group
            catalogFilter:
              - kind: Group
        # tags:
        #   type: array
        #   title: Tags
        #   description: Tags to categorize the service
        #   items:
        #     type: string
        # targetPath:
        #   title: Target Path in repo
        #   type: string
        #   description: Name of the directory to create in the repository. Don't include the root slash.

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOrganizations:
              - tomasferrarisenda


  steps:
    # - id: fetch-base-code
    #   name: Fetch Base Code
    #   action: fetch:template
    #   input:
    #     url: ./base-code
    #     targetPath: application-code/${{ parameters.system }}/${{ parameters.service }}
    #     values:
    #       system: ${{ parameters.system }}
    #       service: ${{ parameters.service }}
    #       description: ${{ parameters.description }}
    #       owner: ${{ parameters.owner }}
          # tags: ['nodejs', 'example-tag2', 'example-tag3']
          # tags:
          #   - hard-coded-tag1
          #   - hard-coded-tag2

    - id: fetch-manifests
      name: Fetch Manifests
      action: fetch:template
      input:
        url: ./manifests
        targetPath: helm-charts/infra/crossplane-managed-resources/eks-clusters/${{ parameters.system }}-${{ parameters.service }}-eks-cluster
        values:
          system: ${{ parameters.system }}
          service: ${{ parameters.service }}
          region: ${{ parameters.region }}

    - id: fetch-catalog-info
      name: Fetch Catalog Info
      action: fetch:template
      input:
        url: ./catalog-info
        targetPath: helm-charts/infra/crossplane-managed-resources/eks-clusters/${{ parameters.system }}-${{ parameters.service }}-eks-cluster/backstage
        values:
          system: ${{ parameters.system }}
          service: ${{ parameters.service }}
          region: ${{ parameters.region }}

    # - id: fetch-github-workflow
    #   name: Fetch GitHub Workflow
    #   action: fetch:template
    #   input:
    #     url: ./github-workflow
    #     targetPath: .github/workflows
    #     values:
    #       system: ${{ parameters.system }}
    #       service: ${{ parameters.service }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        title: "Create new EKS cluster: ${{ parameters.system }}-${{ parameters.service }}"
        branchName: create-eks-cluster-${{ parameters.system }}-${{ parameters.service }}
        description: |
          # New EKS Cluster: ${{ parameters.system }}-${{ parameters.service }}

          ${{ parameters.description if parameters.description }}
        targetPath: "" # Leave empty to use the root of the repo or specify if needed
        # paths: 
          # - application-code/${{ parameters.system }}/${{ parameters.service }}
          # - helm-charts/systems/${{ parameters.system }}/${{parameters.service}}
          # - argo-cd/applications/systems/${{ parameters.system }}/${{ parameters.service }}
          # - .github/workflows


  output:
    links:
      - url: ${{ steps.publish.output.remoteUrl }}
        title: "Go to PR"
