apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: prueba-gaturro-eks-controlplane-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "eks.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }
    tags:
      Name: prueba-gaturro-eks-controlplane-role
  providerConfigRef:
    name: aws


---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: amazoneksclusterpolicy-policy-attachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleRef:
      name: prueba-gaturro-eks-controlplane-role
    tags:
      Name: samazoneksclusterpolicy-policy-attachment
  providerConfigRef:
    name: aws