apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: taylor-frontend
  description: dsfsdfasdf
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: taylor-frontend
    github.com/project-slug: tomasferrarisenda/automate-all-the-things-transcendence
    argocd/app-selector: system-service=taylor-frontend # This is for Backstage ArgoCD plugin. You need to add this label in the application.yaml. You can also use argocd/app-name
    grafana/dashboard-selector: "tags @> 'linux'" # The following selector will return dashboards that have a 'linux' tag
  tags:
    - nginx
  links:
    - title: Documentation
      url: https://github.com/tomasferrarisenda/automate-all-the-things-transcendence
    - title: Admin Dashboard
      type: admin-dashboard
      icon: dashboard
      url: https://admin.example-org.com
    - title: Metrics
      type: metrics-dashboard
      icon: analytics
      url: https://grafana.domain.com/
    - title: Logs
      type: logs-dashboard  
      icon: assignment
      url: https://grafana.domain.com/
    - title: Helm Chart
      type: helm-chart 
      icon: github
      url: https://github.com/tomasferrarisenda/automate-all-the-things-transcendence/tree/main/helm-charts/systems/taylor/frontend
spec:
  type: service
  lifecycle: experimental
  owner: group:default/taylor-team
  system: taylor
  # dependsOn:
  #   - 
  # providesApis:
  #   - 
