apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secret
spec:
  encryptedData:
    GITHUB_TOKEN: {{ .Values.github_token }}
  template:
    metadata:
      name: aws-secret
      namespace: {{ include "common.names.fullname" . }}
    type: Opaque