apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secret
spec:
  encryptedData:
    creds: {{ .Values.aws_credentials }}
  template:
    metadata:
      name: aws-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque