apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: sistema-gaturro-nat-gw-b
spec:
  forProvider:
    # connectivityType: private
    region: us-west-1
    subnetIdRef: 
      name: sistema-gaturro-public-subnet-b
    allocationIdRef:
      name: sistema-gaturro-eip-b
    # subnetIdSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: example
    tags:
      Name: sistema-gaturro-nat-gw-b
  providerConfigRef:
    name: aws

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: sistema-gaturro-eip-b
spec:
  forProvider:
    region: us-west-1
    vpc: true
    tags:
      Name: sistema-gaturro-eip-b
  providerConfigRef:
    name: aws




---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: sistema-gaturro-nat-gw-c
spec:
  forProvider:
    # connectivityType: private
    region: us-west-1
    subnetIdRef: 
      name: sistema-gaturro-public-subnet-c
    allocationIdRef:
      name: sistema-gaturro-eip-c
    # subnetIdSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: example
    tags:
      Name: sistema-gaturro-nat-gw-c
  providerConfigRef:
    name: aws
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: sistema-gaturro-eip-c
spec:
  forProvider:
    region: us-west-1
    vpc: true
    tags:
      Name: sistema-gaturro-eip-c
  providerConfigRef:
    name: aws