name: harbor-setup

trigger: none

variables:
  - group: aws-keys
  - name: AWS_REGION
    value: us-east-2  # This value was modified by the initial-setup python script
  - name: APP_NAME
    value: gonchi # This value was modified by the initial-setup python script
    

pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created


steps:
# # In this case it's necessary to specify the checkout with the persistCredential options set to true. This will enable us to push the changes to the repo.
- checkout: self
  persistCredentials: true


- script: | 
    mkdir ~/.aws
    echo -e "[default]\naws_access_key_id = $(aws_access_key_id)\naws_secret_access_key = $(aws_secret_access_key)" > ~/.aws/credentials
    echo -e "[default]\nregion = $(AWS_REGION)"> ~/.aws/config 
  displayName: 'Configure AWS Profile'

- script: | 
    mkdir ~/.aws
    echo -e "[default]\naws_access_key_id = $(aws_access_key_id)\naws_secret_access_key = $(aws_secret_access_key)" > ~/.aws/credentials
    echo -e "[default]\nregion = $(AWS_REGION)"> ~/.aws/config 
  displayName: 'Configure AWS Profile'

- task: AWSCLI@1
  displayName: 'Update KubeConfig'
  inputs:
    awsCredentials: 'aws'
    regionName: '$(AWS_REGION)' 
    awsCommand: 'eks'
    awsSubCommand: 'update-kubeconfig'
    awsArguments: '--name $(APP_NAME)-cluster --region $(AWS_REGION)' 

- script: |
    while [[ $(kubectl get -n registry ingress harbor-ingress -o 'jsonpath={.status.loadBalancer.ingress[0].hostname}') == '' ]]; do
      echo "Harbor Ingress is not ready. Checking again in 5 seconds..."
      sleep 5
    done
    kubectl get ingress -n registry harbor-ingress -o=jsonpath="{'http://'}{.status.loadBalancer.ingress[].hostname}{'\n'}" > harbor-url.txt
  displayName: 'Get Harbor Endpoint'

- script: |
    sed -i "s|externalURL:.*|externalURL: $(cat harbor-url.txt | tr -d '\n') # This value was modified by the harbor pipeline|g" helm/infra/harbor/values-custom.yaml    
  displayName: 'Modify values'
  condition: always()

- script: |
    git pull origin main
    git config --global user.email "AzureDevOps@HarborPipeline.com"
    git config --global user.name "Azure DevOps - Harbor Pipeline"
    git checkout -b main
    git add helm/infra/harbor/values-custom.yaml
    git commit -m "Harbor endpoint URL updated by Azure DevOps"
    git push --set-upstream origin main
  displayName: 'Push changes to GitHub'

# - task: DockerInstaller@0
#   displayName: Install Docker
#   inputs:
#     dockerVersion: '17.09.0-ce'

# - script: | 
#     cat /etc/docker/daemon.json
#   displayName: 'probando'

# - script: | 
#     sudo echo '{ "exec-opts": ["native.cgroupdriver=cgroupfs"], "cgroup-parent": "/actions_job", "insecure-registries" : ["k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80"] }' > /etc/docker/daemon.json
#   displayName: 'probando2'

# - task: Docker@2
#   displayName: Build And Push Image
#   inputs:
#     containerRegistry: 'dockerhub'
#     repository: 'k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80/my-app/backend:1'
#     command: 'buildAndPush'
#     Dockerfile: 'my-app/backend/Dockerfile'


- script: | 
    curl -X 'POST' -u admin:automate-all-the-things\
      'http://k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com/api/v2.0/projects' \
      -H 'accept: application/json' \
      -H 'X-Resource-Name-In-Location: false' \
      -H 'Content-Type: application/json' \
      -H 'X-Harbor-CSRF-Token: uquRVLoVanrIUQLxZcL3wVsD8IQ7/miuHJwKWhsONgHewkZTbjfOUpiakuQE5mCdrOG375AsUwYEz35j186fBA==' \
      -d '{
      "project_name": "hola3",
      "public": true,
      "metadata": {
        "public": "false",
        "enable_content_trust": "false",
        "enable_content_trust_cosign": "true",
        "prevent_vul": "true",
        "severity": "low",
        "auto_scan": "true"
      }
    }'
  displayName: 'Create project'

- script: | 
    apt-get -y install podman
  displayName: 'install podman'

- script: | 
    podman login --username admin --password automate-all-the-things k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80 --tls-verify=false
  displayName: 'Login to registry'

- script: | 
    podman image build --tag k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80/my-app/backend:1 my-app/backend
  displayName: 'Build image'

- script: | 
    podman image push k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80/my-app/backend:1 --tls-verify=false
  displayName: 'Push image'

# - script: | 
#     docker login --username admin --password automate-all-the-things k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80
#   displayName: 'Login to registry'
# - script: | 
#     docker image build --tag k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80/my-app/backend:1 my-app/backend
#   displayName: 'Build image'