name: sealed-secret-generator

trigger: none

parameters:
  - name: TYPE # https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
    displayName: 'Select type of secret'
    type: string
    default: 'Opaque'
    values:
      - 'Opaque'
      # - 'service-account-token'
      - 'dockerconfigjson'
      # - 'basic-auth'
      # - 'ssh-auth'
      # - 'tls'
      # - 'token'
  - name: SECRET_NAME
    displayName: 'Introduce the name that should be given to the Sealed Secret'
    type: string
  - name: NAMESPACE
    displayName: 'Introduce the namespace where the secret should be deployed'
    type: string
  - name: SECRET_KEY
    displayName: 'Introduce the key of the value that should be encrypted (e.g. DB_PASS)'
    type: string
  - name: SECRET_VALUE
    displayName: 'Introduce the value that should be encrypted'
    type: string
  - name: PATH
    displayName: 'Introduce the path to which the Sealed Secret manifest must be saved (e.g. helm/my-app/backend/templates)'
    type: string


variables:
  - group: aws-keys
  - name: AWS_REGION
    value: us-east-2  # This value was modified by the initial-setup python script
  - name: APP_NAME
    value: gonchi # This value was modified by the initial-setup python script
    

pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created


# jobs:
# - job: general
#   condition: always()
steps:
  # In this case it's necessary to specify the checkout with the persistCredential options set to true. This will enable us to push the changes to the repo.
- checkout: self
  persistCredentials: true

- task: HelmInstaller@0
  inputs:
    displayName: Install helm
    helmVersion: '3.11.2'
    installKubectl: true

- script: | 
    KUBESEAL_VERSION='0.24.0'
    wget "https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION:?}/kubeseal-${KUBESEAL_VERSION:?}-linux-amd64.tar.gz"
    tar -xvzf kubeseal-${KUBESEAL_VERSION:?}-linux-amd64.tar.gz kubeseal
    sudo install -m 755 kubeseal /usr/local/bin/kubeseal
  displayName: 'Install Kubeseal CLI tool'

- script: | 
    mkdir ~/.aws
    echo -e "[default]\naws_access_key_id = $(aws_access_key_id)\naws_secret_access_key = $(aws_secret_access_key)" > ~/.aws/credentials
    echo -e "[default]\nregion = $(AWS_REGION)"> ~/.aws/config 
  displayName: 'Configure AWS Profile'

- task: AWSCLI@1
  displayName: 'Update KubeConfig'
  inputs:
    awsCredentials: 'aws'
    regionName: '$(AWS_REGION)' 
    awsCommand: 'eks'
    awsSubCommand: 'update-kubeconfig'
    awsArguments: '--name $(APP_NAME)-cluster --region $(AWS_REGION)' 

#####################################################################
## Opaque

# - job: Opaque
#   dependsOn: general
#   condition: eq('${{ parameters.TYPE }}', 'Opaque')
  # steps:

# - ${{ if eq('${{ parameters.TYPE }}', 'Opaque') }}:
- ${{ if eq(parameters.TYPE, 'Opaque') }}:

  - script: | 
      echo "apiVersion: v1
      kind: Secret
      metadata:
        name: ${{ parameters.SECRET_NAME }}
        namespace: ${{ parameters.NAMESPACE }}
      type: Opaque
      data:
        ${{ parameters.SECRET_KEY }}: $(echo -n ${{ parameters.SECRET_VALUE }} | base64)" > opaque-secret.yaml
    displayName: 'Create secret manifests to be sealed'

  - script: | 
      kubeseal --format=yaml --controller-namespace secrets --controller-name sealed-secrets < opaque-secret.yaml > ${{ parameters.PATH }}/${{ parameters.SECRET_NAME }}-sealed-secret.yaml 
    displayName: 'Encrypt the json secrets with Kubeseal'

  # - script: | 
  #     cat ${{ parameters.SECRET_NAME }}-sealed-secret.json | jq -r ".spec.encryptedData.${{ parameters.SECRET_KEY }}" > encrypted-value.txt
  #   displayName: 'Get the value of REDIS_PASS'

  # - script: |
  #     sed -i "s|redis_pass:.*|redis_pass: $(cat dev-encrypted-pass.txt | tr -d '\n') # This value was modified by the sealed-secrets pipeline|g" helm/my-app/backend/environments/values-dev.yaml
  #   displayName: 'Set the encrypted value in the values of each environment'

  - script: |
      git pull origin main
      git config --global user.email "AzureDevOps@SealedSecretPipeline.com"
      git config --global user.name "Azure DevOps - Sealed Secret Pipeline"
      git checkout -b main
      git add ${{ parameters.PATH }}/${{ parameters.SECRET_NAME }}-sealed-secret.yaml     
      git commit -m "Sealed secrets created by Azure DevOps"
      git push --set-upstream origin main
    displayName: 'Push changes to GitHub'


#####################################################################
## dockerconfigjson

# - job: dockerconfigjson
#   # condition: eq(variables['TYPE'], 'dockerconfigjson')
#   condition: eq('${{ parameters.TYPE }}', 'dockerconfigjson')
#   steps:
- ${{ if eq(parameters.TYPE, 'dockerconfigjson') }}:
  - script: |
      # Run Script2
      echo "Running Script2"
      # Add your commands for Script2 here
    displayName: 'Run Script2'




