apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
spec:
  encryptedData:
    GITHUB_TOKEN: {{ .Values.github_token }}
    AUTH_GITHUB_CLIENT_ID: {{ .Values.github_auth_client_id }}
    AUTH_GITHUB_CLIENT_SECRET: {{ .Values.github_auth_client_secret }}
  template:
    metadata:
      name: github-secret
      namespace: {{ include "common.names.fullname" . }}
    type: Opaque