environment: dev
    
redis_host: master.gonchi-dev-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:  
    tag: 896
  replicas: 1

secret:
  redis_pass: AgANC9FT74kV6MCOUjSH/FGo7uY/uiQhWqpJlVe07Fz6wzILrLiVKQtAFEBVljPyG5ZwOQJyb2dJB/RGFqzJZaZD6x7DjYBL04PbmrjmMJ/gJ54Tezkk/ybMlJhhjZomdHFgAkvPkRHp9NGIBgDRTuMlXKxPDW72njqhxa8NR/Rg7dN9cHVDEHKYhwrvLSMrmqztaOefSUa6LWavdLXKQXq5+yA+HDNH5uAy8e2Mi64U4vLuEiI1WVxOYZAARjjr2oj/blZe+0WZKyQtGPcvqtuPmfbUQNoGkq2xw7zq3ZbqmPochx6EQPobQo2sdX5bo6zjZy+3hXb+6pQG78vwS979/lxd8JK6HfxZXX/qY45Zc9S2LSnqnWhcMDp+oqhQFvLG4deyHbZPYoJ9stMRVhTEYVndsVsMTvBAFvVJ5XAucqG5m1MQriVxwLlrtnUJyihm39hHOnk5Riue6jHRWZtG3KwL1yILzrTeXYKBG7DlVTjuKxQ8i9D218O+SzmZzW7d3xupUtxU3qPrlZ/NsJUse+wv2nOSIWryHRr5WTNEczvuy+jFBugpDPenovifbLFDipOXmZMXjsj9/Af1WnLul38tq2kUAEanEheAlkGx5lr9n8tre8AcJtcVP4PUylZdX7V4ZkT244LfE5LHa9LnKRWKSQKU1RQMq32PrY1RQ2wOe8TaSnygZJzMJLtF3aS9rM11i33l7TsWItU/qiaeUEd9HU/nxjc66h8= # This value was modified by the sealed-secrets pipeline
