environment: dev
    
redis_host: master.gonchi-dev-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:  
    tag: 896
  replicas: 1

secret:
  redis_pass: AgCxQR77ykEOm9IKqsEr3z7EatXlgMAp/gIrC0WacuFpVWPpnAGPjiLHQjq4Od2jYlXYrL4tw0WYf8SOmTTkasZApE+4K/6xwRONqIoUKmkOModHzIStky9Dk0gDg1Zhfq3mwNJiZTSSokjpaihic2cnAg3JC6B7tXF+YYtrukI4RihcNwhVoaYxBC82uzav6J1gZD4cteOcX5H8XOFZGvUD2BP+rdZajPyell6jaFQnYpCbagDkSM/1XCCjMhco/mByqtxqXw2yD9R5Y1Np07ZnA2sXMm4dXwl22iOGXILwN1MGB8dfptbuqq+d9kSJn4rXOB1DwXCg/jCIOYbW2M02mBxkKkmkgiqqRr9piejpcGfD94dPJBywWbxKh4ukL1dcrbgz4tTJ5/WaP7D3fNdWavldc87hE41iUlSwy8yINj9026OUlFPXpZXnoaoWDjrPXSkTyRpHqd+wejB6UI1e5dd512HCGKY5OvUd/MQ9aPp78pEHoOWRJygXKc4wtyrwA9rWwD7rGd/SnC25cxfbyhcyPSrxEKQX9JhymMPskYQvhGV/gk+67DrkDjHQPnXnj2QiJN6QL75238pqkDAAINi7tNJ17S7wv4gX3tKDT96rtnkunV4pin0FoFYKnydXXpUzL9Zqhm5nc/Qnv7HE9g7FDzneju92d6Q2dYux0q/n4O0aheavKAekV4xFEVgjupEnPYS7HNz7Q80zcZFbt17zLg+EtUactTk= # This value was modified by the sealed-secrets pipeline
