environment: dev
    
redis_host: master.gonchi-dev-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:  
    tag: 896
  replicas: 1

secret:
  redis_pass: AgA5uO9/G6WH8VEWps1Bx06dbY/65B/CtY8yHh8YMn2WZKR8QXPlLfF0prKxlvD5RAcmbOFBh5IhH0Z/oqexYzfo6LzKERoB+xbh3lqngTA+lUm2vAuDZ0JNaQU4Mb3Dla7ZdJRr0gs8HBzXTuQddvmNxAajwc4L+HQd3HJbAYB4Mcc3YIxHZTz9QA44rGC4v93Gs0XbTMI5MAzq/7dzxxXiq9MexbMQBth/9rXyhR+yH6LvqsS0zv0mGSFAmb+XxFL5kf/Di4hNdqGLSDBh12aKaFa3QzcaTfAY2VOf0oJpv/6py8WcaF5xnz2h5qB4tDXwhiNj9NbFJ4f30a8xAHG2vlhvXilPARpjTptNKtbgsXVf0Gt8TV4u2saa0COFG2F7DJFUMqi8TIOHbCzjAGLsHOfOETWl5PvHVmZjiIecrLk03RdPe4Yao2d7cUhxy6H3glE2DZwV86+JxNsbbJatE/m8WKboh9P/WUxlXxtTDYABpMPFGxmMxfKVONpOhEsCzFA2mxZE95RIoLp6z3Aie/8mwLUqUnm0sSvrClx+o+fDEaIzqylsufoUesY7NeAYfk43LW9nN2MIX48V9SfEdTr9N4BcE+u9GOPIWaELRR/48KJkx9tdKRYLCYJEEaEBem2jDCVhvQaasy0U/673Y5TxRS9ZjHfPZYepPOjpRSEiKcgLlfyrI0fHxY8lrGsfDkNe4qM6GjanaSxYjCq1ky4TsV5ka4sGMr8= # This value was modified by the sealed-secrets pipeline
