environment: stage

redis_host: master.gonchi-stage-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 896
  replicas: 1

secret:
  redis_pass: AgCiSVcRu0/1wKoNlXgdgE7ZV7sJ1T0ivH3myGXu3ajVhtn8uy3wzSEaQ5tGNjJ3zzBBDeRIrp6FaacfnivE/6rnVfymlWjEh3xg4MXbgmauDdzPFLTTSB7GZRmzQ0417uI+mXvlpy/mdVAXqzUUIHJ7Na147JByHuy9XpQJC/wIGVbiOXyzFgX5MZwE4j5EqNAeDj1xQdIAE7w7/yiIdII7YMBRCpRgL+rM1cZtrFr559kIQpNkVhKzzkNWc/263R7IW4t7p44DPyzn6oyedrJXih7WYsdHjURVSfvcMKKX5AuTdQtRjjz56A126iwBkSjZwEPkGu4BEI9GN8kCJLAoVVbhFv/nqb6qnmazDZRLe8ZjtmuQso1mj11HtQInT6F4DpBFfJyKRn68CMnQxqInnv58tvCTWCD+CSPW1gUmgbEr85mPexvReX0KXaA0Qz/u5tueIklaXJUqaFIS5hTH/86OpGbNrgO82+LtM6zQG7v/nWsy+vsndDux7C6fxon+iFfFPJFW5R9CYVda832D33chpfPHFAJgGvMbHxJXpcaNI223wDekxv4LJPAslSuQ/egktmFi6ZabfNm3m+My5ukI/6OP0+IvhKARm1CrKtmGxe9r3NOW806IyZAh4Ci6AhWEj4KAfN8ctQfktPWLCDQ8LViS0z9y4dJ/Ao/pYA2qcVx4GoLV8eHF+WRvNGVCb1F91efV3kkbIKtY9u9NN/LvlZ9U/4YQGH0+vw== # This value was modified by the sealed-secrets pipeline
