environment: stage

redis_host: master.gonchi-stage-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 896
  replicas: 1

secret:
  redis_pass: AgCBklhCLYwzNZTXmCDTWvtXt8aH3EsMOOb0JweGSgUrYjHSS/lTHGid8HlhyJ4WHUnVmT64oj/ZwYgkky1gognhgv5s2oHEr7c4lun2YG30lU012JoLnGUwsJZBkmHa9lIZfdHqjUpjfVK14cwCQnrf2D+7XAOj8SlJ0RTR4vpCoXeF9SuCY6rvPkfNwZ2cOiUh12dEJ+HsAKfzEsLR7VWyP76+GWyT810m2JubphIbopgC+JCKCw9NuXEj4RFodLy+QHqGBwZD3XSvAIpA9KpcMzbUCp2hGdy5UFPkVu2SViAEx24UGnNg9cIjaFwsxVoAYV/VoWsW30we+FEEyIq2FB+Pq9mpSJxuoxKE085f4o+lN1BEos2l+l81lBgJQeqbrZsinh8qb88+DRCKrB5IiXNah0R2Tc22/0mMLn7qB6wVKhPjEDj8+28nsUZohHZPWE8xteiOtCxAD8t/UNQt/Mle+ONQPuAPvWWFexGq1Vu0W8uuq2Wjw+BahxKBD+cfgpKfEpIEIasu8XzIs1s8oWaRp8tT0W32qJpFfYpXDFytaXca6/2pAb/aGPKuFteS68WiTOs4yTzBPLUeTeLBYUH8CKY4KUIb0mp/3q/zKDGPg8FTaIKns/9r2CGQ7wgf7LLjgqTs69Wh/q4rcJa0mglUotatw/lz3u5LoQ4LfPzMxm87d6htFoIWPewdG5blVnR9aYQrN7kaBnT2KQqxXpCRzHESkIV+ucUvtg== # This value was modified by the sealed-secrets pipeline
