environment: prod

redis_host: master.gonchi-prod-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 1029
  replicas: 1
    
secret:
  redis_pass: AgB2dtwkCOyGPvedAGulcYV4UJ8gjkOpGrV0KD0Maal/5fzIw8irtEFGwKSTrujwkLQAjqZyTCYajiDPWrVejxI1w22C5USCjx+SGU0gNa8nWvTFpv5iQOKjfKmLzzHiz78nKuUWgastSTw0kvOreyrvJrcxVKtU0nlEj45KIuLCTAB9sECY8l6EKJjhg7PdPupJt/DVoRrL8USbhim3YARooJc4ZW78rPgUr7x3fdRxvfjoX5vODCGYkmKd2IgGvi8z9SCiI5F/iYcbVYvrWNtU0rXpFqUAfpRvE47GAu/XEfUdTxwjhxXf0Y6EDWqXBsLJ96KCTD6iM4u4537/k8do4vmSqHk+aGtXC2TPwhVAvlhzZvT8H6pmH+EXYLbcA0/ELH0NLI1ceTEf20FMQJU96OQCdpkJwZjdEy36BMvWwVQB4AnwCf8ve3u1B/RZFF2nHsk5psvp/EK7jAG8O1VqSYSCLRki1hyag07B3sfk1tsuC59KmCwBAuNJvBsexo9OhJXeX0Ae8KKKowAV2EfkBFBmHRyD3AjPe/zRbWu5rPQLse6qwisfwxZqZ3tLZTpMmzRHVQFI8XDnSpAJjIDTvKgKKkTKkoGb/TYRUSwN0K4QD+boGgyLXC3S6r0QHR7/yD18BXlj8nowbTmY7O6k5fUgLh0S1j7xOFANCdhR0qhVWW1qyB+kuwn5oSeLStEX8qzMfUMIFsU0hld3J+s9Rib7yfkgwBrr81Cy # This value was modified by the sealed-secrets pipeline
