environment: stage

redis_host: master.gonchi-stage-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 896
  replicas: 1

secret:
  redis_pass: AgBhi5skRT2XC0mHViGbmUiH/HtzLitg01IMgRfES3zFuqHf4/ccZUtJL2uyczqwsEgSiBMFjIfXCgkQI6ekSHhLO9afJvkDo2DF05IExM2ek43kKO9Iq6SvsbZvqkMW8Yntu2upLLrX5be2MK7G7d5o+8UHtYf/7kpxMAhtC2Tzqzdm9v/n8Lln2Rn5dH5de9zw9oqGjhLP5LGKX8vDuuXzr3eg/ugh/6wWzewVTfcexkcC6mMDihUyZgVdAVq/+/W0EgiMYVWmQEckDtt05oogR02hPI6Lg+VhZ1jrDqaiv/dfTYbqbfFhNdC62z5DSmGAhWVidQnDXJNjmwcuttKsV163jIomkCsSNVViRs4DnOcMV4IVnREpgQ4VKgyB0itBHbkonIJRSnoG28SmhzD/yRS5ifoTPxelHOfY6xVGnBa1I6mC85l5TD9XZ16t6etkZWvIq4N3dxo/rLGOL+1crcoUW6v3FmuB8srvZYqPD22ytDBCFz4Dm1bdhSBtxenkXPK7YuAPEzFm2ko2piH8MaDPlyIqwmK45CBopvh9pCkNwakUhbVBEwJYWx7fhdp1SGCUZOfs8eVA28vxmfJYicFl9ZoC7V2h20ulL5bBEcs5m4YMwiIl6B7iET4+8Oxq5f9ZVx/HwGO9+zcV+RFv9Fq7nEmtOgFBUphE56HcBEBx6Ki39/8E8p4Jt5OE4HvRQCLD8wlKZhPRNyon1dZjIbKbxy0Azr6X8Hivfg== # This value was modified by the sealed-secrets pipeline
