environment: prod

redis_host: master.gonchi-prod-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 896
  replicas: 1
    
secret:
  redis_pass: AgBAwC7C6rWtmgsWDiTIHneTP5PUHHOpuFya6kZ6rSc3YNCfXELIVJ4jBNCLzzv8gTa2xpVYA/Y/UuIZ5v5pcnSqS62dq7MuQG2oZfbGgVi3EzCUMrI5fz/kq+5prKZKmQ/zi1HAwWjzhNNzAKT/JlX8RQzyiuNCFkkGRIYVQH7FbyJGg8pmY5pT1CAxLwhB2GTdG5eQ6WdUFJbJUnx0GNWO5dZKVMHjINREQ8dQ+uC0SrDk58hBCUUHpg1tiximF2+oxAHugnph6HzGEeAO85wTkM0TVvZVuGwwBku44HBkKvfP+bSaGDpzlkkMwISsSDeRIW/M/LghCp/7mgYnM5H1kcG7JAjei2VoGLhCaYLYjbrC3snK1nk0EdwemVNoCxuc++iLkU+VfzYoduALk+xrW18BkiscOXXIjbhYEXNdTRV8my/IKikqc6byD9FFGMCQJnE00Xv1ocYCihpODDv8MqeHXdYqMGbDxFvd2/xHkeUn5p0BWhVz3RQ5fuowBcfjVW2w36zWrTCdg9k3HxqadZEEwTClap7k7rqSpgpau5cbN59WQ99zOO96CIAOfBMPB341Fu7iZOKS8lRo8Q04sgiC6dYVmYST+xLUoxpR2Ltiz0fh8bpT8fFuahQAZKFUp/ncFcMLlMIeHEjD+d5ze4DOrnqhJoLzWxH8RAEhhKTerahPbtIvuJ0Ty1iY0nSB/eyj3Fy9IWrt1iMZhslMR65ql7D3wUUdUDz8 # This value was modified by the sealed-secrets pipeline
