environment: prod

redis_host: master.gonchi-prod-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 896
  replicas: 1
    
secret:
  redis_pass: AgASn4l9dmLO61kLtWhDrD4WpOSdGPzxMqc15wKtJNbICdYYWvOhmIqbEgf2YHtk1w+HrWMct35AK7dZi92oF+qbOtmOLBKh533WkxsVxHSFIlMCnB6f2jDMrAICl+dFnb2k0pzy0k+/KqVvn5etocRqXkpmLI4gE8G9YBr4AmvDqHpVq5q/Z2CPmz9ZtWJZpKH24904YOGdfiilBxnxpHU97i5ZMAdOamD+7BDHXQLsmb0UYSq4XbId5nJtI8irBELCp0twB99zA4A4vDFb6SfRMxUx9p5a/cYbn9iuT95aHJmIYYMuK7Tj7zEZOmIWPIm1aNIH/ScM/6m/4va/bBd60PSzqugLMW14DsHpJI64klrjfWyi5GSEW0qQPyQeKEecAh7WjDoCOB8gZP1t3DK4Jz60RJZ0jrucStmegh6DwCdU9mw1zycO1ZT1a6sXToxoMm26mhKb1SSEU/sx2QWuh5Z261F9DyrFeXanIvybIy4ZYNk5eTDHTBfpTFtxBRfiUOFRGnpsU80zdp50CZpIOU9iIgNepcYg4sEp/4RI86HNp36rLvWDpxsxa2/WcMAOIRb3BR8EUQYDjv5fFL2r4wtIAZYbO3u7agkxq2iCaML6b+TrK7361SnTKyOkHNWIw7UuHLWEMhv4owYpfnIqf1AesxzZd7PsUDVcL/TzTdRQngRuGZvbS8Lj4nZAVVZrgX40/cL/6lCUqQhd1xMl8zUFmgjlIGx7PrP5 # This value was modified by the sealed-secrets pipeline
