apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  # generateName: crossplane-bucket- # This does not work with ArgoCD because Argo uses "apply" command and generateName can only be used with "create" command.
  name: ${{ values.system }}-${{ values.name }}-bucket
spec:
  forProvider:
    region: ${{ values.region }}
  providerConfigRef:
    name: aws