system: meme-web 

service: backend

port: 3000

deployment:
  labels:
    system: meme-web 
    service: backend
    backstage.io/kubernetes-id: meme-web-backend 
    istio: monitor
  
  image:
    repository: tferrari92/meme-web-backend # This value was modified by the initial-setup python script

vpcId: vpc-00f8fb7c3de914a17
subnetId: subnet-0f12c8d398e0ec6e6
# securityGroupId: sg-0b7bab67c05dab563