system: meme-web 

service: backend

port: 3000

deployment:
  labels:
    system: meme-web 
    service: backend
    backstage.io/kubernetes-id: meme-web-backend 
    istio: monitor
  
  image:
    repository: tferrari92/meme-web-backend # This value was modified by the initial-setup python script

vpcId: vpc-0a04167a84397d2c5
subnetId: subnet-0f038a9d4c70de3dc
# securityGroupId: sg-0b7bab67c05dab563

elasticache:
  annotations:
    backstage.io/kubernetes-id: meme-web-elasticache 