system: meme-web 

service: backend

port: 3000

deployment:
  labels:
    system: meme-web 
    service: backend
    backstage.io/kubernetes-id: meme-web-backend 
    istio: monitor
  
  image:
    repository: tferrari92/meme-web-backend # This value was modified by the initial-setup python script

vpcId: vpc-0fc19bd6b001e19b2
subnetId: subnet-0f17c1b8a0ec1ae20
# securityGroupId: sg-0b7bab67c05dab563

# This doesn't work in objects of kind Resource. It only works in objects of kind Component.
# elasticache:
#   annotations:
#     backstage.io/kubernetes-id: meme-web-elasticache 