system: meme-web 

service: backend

port: 3000

deployment:
  labels:
    system: meme-web 
    service: backend
    backstage.io/kubernetes-id: meme-web-backend 
    istio: monitor
  
  image:
    repository: tferrari92/meme-web-backend # This value was modified by the initial-setup python script

vpcId: vpc-00d397e6d23166bec
subnetId: subnet-0731d5c646acb9797
# securityGroupId: sg-0b7bab67c05dab563