system: meme-web 

service: backend

port: 3000

deployment:
  labels:
    system: meme-web 
    service: backend
    backstage.io/kubernetes-id: meme-web-backend 
    istio: monitor
  
  image:
    repository: tferrari92/meme-web-backend # This value was modified by the initial-setup python script

vpcId: vpc-04045616a38f17911
subnetId: subnet-0adb06c80f323a0f5
# securityGroupId: sg-0b7bab67c05dab563