apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: gonchi-stage
spec:
  encryptedData:
    REDIS_PASS: AgAYyZIQTuDXYLFEeXw1keOrszJqXvzGqdluQQkCixE7FN+KLx4cKn2LMllux0w6B4m71ZgOX0cD4cddgzOwvu3J4/7HruWpsBr55A7rNALSrQt9U6E3pw4f4pli/HzqeYfkuAAwUpdfVSQaS4X5p2UoGWouhQpVaXHinr4jHuy5lwkQU/EUTIE3lK6CK4vdNEgDvJgCYfU7Vh5nVBTcXFaSkSP44aRLAyvusj/VW7yC9c9chNOi+1yBqFothadOV1pWwsv9ixNa57bubdZwCY/6XqKd9/VIa1hNnBDq6xzJeuojCH9XEJgHeoYXkhYoM+UkACuO+S+leLX4TaacTdwnctBrM82M0vOi4LXFeWyoSekBZETDI9RwQd38fV0quNKoth8qRAhdsc/1NyMTssE9C7nH6XDxRZ65SsOPfewWXWiny3b0q+1pbLKrgoIVyMnyMCirQ8LVHy09mk7qqT2lsZH5KnqcSIMw5t4w/oGVF+H8RkH5z7ifd92n/3WQhw6Epf94ryQ3F6UPHLXWNw9A0gPwtaAliklG3pccHAfCwClnd0nhpCEjtlnzJMz1VzDfGCMDekAq955zdw16Kze8/zES15G3FyTMUpz0ZIPbSdbeVyIX1pN+kYbTfd8ojyrn9S0n133MF4XKIDp7NvNb/V7ZmnACruBswOCG2GNc+P934BVw7n9Eu5qmCrHP9fnnBa4gtSQ9vBNU+kTLaatD634++ULueaToiazCqA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/instance: gonchi-back-stage
      name: redis-secret
      namespace: gonchi-stage
    type: Opaque
---
