apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: gonchi-prod
spec:
  encryptedData:
    REDIS_PASS: AgBs7MVAGNLGXJbU1xInkBPHVcnQRjrRvBK6dSzAhO12pFscTdTvYsS76bd91t23NrM0MYS+vfcvVr9FGQaonFb3RJSfG1JzOmKZHw447k+mnF6jtkFQ+sZzyXLBD1M61IJKne4rAPI6SHnATxTy22l6KADGlirqNIb9jkJV6bSg0bEWKpW1fKgGDHl1y8jWhmfyPss2hyQrDEpufikw83LOpqUtBrELZXFyn8dZCsrBip0mJHzzb+EhAtdbPJ9xEI55yQqhGl+jcpQFpXj6jVo0TG1LlNCMvVUcTsFHqkhmtlGQHWzMTXPlxATSCjYaHJrRqzbnmd/WHAEQH+wt/ajvh84R1JmFZtMgsGAh1LBak+zjQBRLvaS1iDjVhRd9nD4eL3ro+bCz2bd4luVB9TU4UJCwfU7sGCO1kfP7CqzFqACIiqGnmPNplqiCAKJ/wePFDR64gwFE06DMfjL7QqoiaJQTQx8cKjZLAN8o2jIQz58ky5kfkjrlKt73jeDQnwMYc0z9KSQWJ95WwZjs4CgFJPYrUpQzBoZueyz0HD/kdyUeR18AAyl6bVSCwVhfpoAAj1BGCeJRViVW5k3pbnEbvv3p+zHCG3GuNop+S5n0CB+/5RhcAReT8EqWR3nEKwPtuZWFh8cY7DvnEUfVeqRVZi2g2EIWBA2ZtzAKU+7ewpXRa5ID88zTX6dNI2y9buX/9f/Tw8+Yt47cBmEYY3yD766ma0Cw6EPLdneO
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/instance: gonchi-back-prod
      name: redis-secret
      namespace: gonchi-prod
    type: Opaque
---
