appName: gonchi # This value was modified by the initial-setup python script

service: backend

port: 3000

deployment:
  labels: {    
    istio: monitor # This label is used by the PodMonitor
  }
  image:
    # repository: tferrari92/gonchi-backend # This value was modified by the initial-setup python script
    repository:  k8s-registry-harborin-3fc40329a9-1560970000.us-east-2.elb.amazonaws.com:80/gonchi/gonchi-backend # This value was modified by the initial-setup python script
