apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: sistema-gaturro-internet-gw
spec:
  forProvider:
    region: us-west-1
    vpcIdRef:
      name: sistema-gaturro-vpc
    tags:
      Name: sistema-gaturro-internet-gw
  providerConfigRef:
    name: aws