################################################################################################################################################
# Explanation of why this is here: https://github.com/tferrari92/automate-all-the-things-transcendence/docs/crossplane-notes.md#cascade-deletion
################################################################################################################################################
# apiVersion: azure.upbound.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: azure
  # annotations:
  #   argocd.argoproj.io/sync-wave: "2"
# spec:
#   credentials:
#     source: Secret
#     secretRef:
#       namespace: crossplane-system
#       name: azure-secret
#       key: creds