apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: piaggio-gonya-nat-gw-b
spec:
  forProvider:
    region: us-west-1
    subnetIdRef: 
      name: piaggio-gonya-public-subnet-b
    allocationIdRef:
      name: piaggio-gonya-eip-b
    tags:
      Name: piaggio-gonya-nat-gw-b
  providerConfigRef:
    name: aws

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: piaggio-gonya-eip-b
spec:
  forProvider:
    region: us-west-1
    vpc: true
    tags:
      Name: piaggio-gonya-eip-b
  providerConfigRef:
    name: aws