apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-example-manifests
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
spec:  
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: crossplane
  source:
    repoURL: https://github.com/tomasferrarisenda/automate-all-the-things-transcendence.git # This value was modified by the initial-setup python script
    path: crossplane-example-manifests
    directory:
      recurse: true
      jsonnet: {}
      exclude: '*catalog-info.yaml'
      # include: '*.yaml'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
