apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: piaggio-gonya-bucket
  description: gonya bucket for the piaggio system
  tags:
    - aws 
    - s3
spec:
  type: s3-bucket
  lifecycle: experimental
  owner: piaggio-team
  system: piaggio
