# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   creationTimestamp: null
#   name: harbor-credentials
#   namespace: gonchi-dev
# spec:
#   encryptedData:
#     .dockerconfigjson: AgBJ1pLX/ma1Z/R/CvuRPY1ko+sF5l0QParOvhegUQx1+Jeo53CAKGp4TnhjH91U87PwK6pD2RnmIcPPQIeG1dAo66JhrMM7vj9p7HbkEcqnY9zfDTpvY25HEgQUCRFXLBqjkLMMWEOZ05pDKmg+KdZvAwgo2cDw9H5eBbXKUwcPIUHFDMLjz+fTjERoHLuwen2jsAI31oVzQU1J8bNYSnEo6u2xjRof1EiA3IwwSvjAgyaj+AvpSlqpWqw04z/1cBGufcJCq5xvxdkvXGqWRWk39XMeB2cWAeDBGJEdBVpNl2l2wD+FOT6O2PDYu7/QyBdIEgGEVML9mZl2OAnybZMuo8jwsVhNRtcIzR04K3EuFjlubbGDqwR9mTYmGP0USkPYb3XK3ZaqFnN/3t/RasVyqAsze62TzMRUvI9/9hwSoQyhvqjPp3+nCU4LmaswMyxTbqlaI20w0CDJDZFeMY6a1qTgw6Pm0vtwSC2nPb4zjWjFzxalwZwTPdaB6iXASks5ebZI8poUPi9Qkf7CKr4Vqa84jlRTycoQcgY9cSI2ho8nNoncOL2TVVXdHkNeox3LXAXrbSE7zTN0fmhkLEfFRwlmIIG4ks7Y2vcnre5g9bovAgKPF/8j9oUckcV05+vTzkcWNzqexbC/7TnNTNzJcFdHSEeJZ/lhrNQXLZEpd1RnpYs1K6nJ1RKLrbgQqSJ0erWnpg4GnhC+hUuooJ//xp5O3fOy9tPmX2VRoV614zuY9aLM2Pajxx/I+pAaGzt0GPDhg4dZNOzCrBr2/v0sSZ+qxYRIvJOSO4ezNZGqtKXkCj8NDr7L+qbycl0VYe7tVmnJcKEOtEhqAVQEg1Gq9V09IWMQcUGPdmCEaMhZX1W/h+G1qJ315obCI1ZFDv6H22MxjDO+z2FelHrYbJ4oH9pVP5w1HHziG6ZM+R1Rm9jqUb030OF3rRRRF5QX/1bov2EZ
#   template:
#     metadata:
#       creationTimestamp: null
#       name: harbor-credentials
#       namespace: gonchi-dev
#     type: kubernetes.io/dockerconfigjson
# ---
