apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: gonchi-dev
spec:
  encryptedData:
    .dockerconfigjson: AgB6w17TUPgcbIYw/02NtGUSN/7OnzU2ppyPcEuSvgs7b2LyBUklMtPUqXNC8MjAovH7veyHecG2xx5Myz6uF8uOzvOAQQ3vW/nbuCi9kxxlFjkDnIkiAzztWzGN+pFkvSbf7JzAoaSlSB4cn8gaodD0ZZ7e9s6EwwHeGeaTnnmUAX27vAaUsoZYfCOMdNBJg25v7czzv/vgBCGLr+j+zG5f2M2Dv8BWzviEJJMbQ1aEFoOMARZVCg8dRncBWLtJfE0MWzNN3Otq+ozl1Q64CvZ/ldcX/37tuNQSJ3UJ+TwdA4016LYxzPDfH6TjIRtQXz5KVGMksAinrH0+hAOfEghAiNBdhgC6p4bWM6LKiNwLLWyza1dgp/Hv2MNEyoi9Z0dqo1AzHMg7M1XdnnbiUsCaoo4qJeO9GKVeRo/xproD2hAxnQVarv9kiXcJ0D+QQ85nSfy5NcUTWv0v+IbQsDG0JBntyHvacz+7aU6cV5mdUz07arD/wYWZBDYM9lNpcLleqA5cB82cjgB1Dc9HcDWU66OAPKyK9rg09AjVj5y4mRnOpBm2vZazA4gpqQVU7a7bgaCie+PuZI9fAndyme8uJfRYLbtBqWXsjZMeVVPm1EVOSlrXAunadtQYQr+I+oUp7BkBuuCvIZSwOcSgAVmxKLouYTBBJFlfkC+BHDo07EIFAiHnEmBw7NOHeUcccIv501Y+kD4RvHAU1eeOhDOWLGTyvKfu4Y2raM10Qi8euEW2bHW7WU2pGGEm7ApJ07ldcWjjA1zsM/kPaCedOsKB3m0sj+2uUdzv0mIJnJOxAiHl4qFhf4HATTSSttKNsMRNU+cduvF6/tUOP/BViAIedhB3azArfb+Z9V61p4ief25jN1E/JkuXs67V+F0Y9VO5iHvzm7XQ4icpqdqNvjpMLZVqx555+zsVzrU3HLz8UxXZREQLX+WLPbJsG8FMMqomwzIt+NcAt9vz4VDhLpWj7XC1RGs5UNn2YB6pNQ==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: gonchi-dev
    type: kubernetes.io/dockerconfigjson
---
