apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: gonchi-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBnNVuyJ6g0swhm3gN6xa24sCChxodbxzoNAhgV3l0ki+ZLBBrNDh56RTqoc3so3avTW7I8irvIcyaBzmX8uLe0QSy/GLoKHWZBu6bmlEzkjvzSzK+sAZzLzoGFbcofcvqr6WppIKOGhK2ohT6tKlGcD/rZUBDmfWGspTya1866B1WwFiK0AwP3CmrwGcDA/2ybgXPzq06EC5hfp+HO7aaEEWFsjJF7Fr4YW/nj2MVZ6XEt/Voqi606IiY/+Pqy3jEuwcQ3cbg3uGcLeEzfuonUcU6innfwwivU9b71l5phbz1CvZXJ4XAbYQoPWEqeQkw3FjubGZHp5nqX7VLQAsQUqM2570OvLTEzc6YImIgE6gDMdjEhmrOhf0wVsArYptWJriZKkOJF0Pr2egbO7eshLSxDz3T5kdnEzWfSgZGfjqV5AwzWuiXOScl34uulDw4LjV8yUuP3/Rv3ZJwniy2YoKYBviOagJTqcOIJHMuMgkGJqX5OM+WKAnKX2HVilzoggLjKAmeYXwjx8owrmjvGp2t4pvDaIvOB8Wn9B95A1/dCrJS7dqpSQYkEB0ScRSYobSeQWoTMzXfQbJ2v+td2dynTS8/mRem7GHSbK/Fl0akDReQpNXuEpggcDnPkL4lk6H3UzNyHtrLNDXN/Y5AaTMNP3aRv/ce7doVre8AUE7NxPGNx9a4MKjjat8U8Fc6INthhvd0pgFS5fP1uHEtQ9CGLEkDee3kdWxjduNhJ5iaC5/OO5yKVrBQ2YUsTYG5DNv69JNGX37QhONGi73PNUH6v49umWRGQPe5x01WiNKr2CN9SrAUigHHiik1BhrG2Afpa+CCtxTt0cdmXgnBq/mpRfVvBSVISoxyC6mndpjc5z0stUUjikfcZV7JOulvD4zJSTtWb1bp1Wu31fVocUgAsA6uUfGV+2LYbgeixsn3QrycnRonA07Z8vJgI7WYt3F+2iMF9c+cM6+1gXjoJ9JXE2Ch6Mf7UPxDfUg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: gonchi-dev
    type: kubernetes.io/dockerconfigjson
---
