# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: prueba
#   namespace: gonchi-dev
# spec:
#   encryptedData:
#     PRUEBA: AgAcrPPttCpoM4PIirCcEMkf5ZJTuF1p6u099fVSw2vLuFSMwcLkpE5DDZuN+u5sc5LoKKKALfWwUHglEo5z3L/EB4vIFyM+HO7KTcZzXbMt9WT9WIArDsSbcvcXTjQyARe3vKBAIQDaSg1MzMBEdISUQ2qSFMrtlZyVhB+ao9y81Eb+dv+bdHZbDZ5ShnW9FCarpJj5JvcE5os4pPh7ac1gjC+vXOhhCZ+hUfUrlSycwwaXuFzWjvC2DssOrgxT9eH+NnehwJ2CDkHwSuqB0ZF9yds+RZw6JM96oNIwVIz23P95bSgjBPLz1a3uyXp/w1fKHviGXjO3cDvdwyToP/aV6Z4XqNPS9/tx7J1BiZ1bd++45V55zbNI4Jz9VLkSvz3K5Wf58mVAwrnlJb6SMvA2pPPN4GQ2kUpZ7l4mGmEeag1x2q3/XEfPosKazcRM4HgGdV1x7FrdJLMtNXi1QeRbwxZ9UJf/i0c3R1OA6w0HwBJlkGcXrtOTiQCBm9RnVzIKtu7WbO7D34Dlh+xYskn6zmmk+2vfgrEeK1zFaPJJ0WMz1wFfckj7o++dP4vhu3iieMJFt+sH8rp8gHkIDPEM216dy9bcQ9JlQ5R0H1SoBjiX9cXw4NtMhkUk0Rboi8FBzydd02EkntpaBwf7Mc6NLM7sx/NkACaDFRPl5BBmVtqi8dbcdOO/686ZSLhqrfiNgbftNmQ=
#   template:
#     metadata:
#       creationTimestamp: null
#       name: prueba
#       namespace: gonchi-dev
#     type: Opaque
# ---
