apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-sealed-secret
spec:
  encryptedData:
    # REDIS_PASS: {{ .Values.secret.redis_pass }}
    REDIS_PASS: AgBEaG2nYSS6HoHpZKYfsVF/1lFbwr99zqLBul5d3oT88GksXO4vyIhpo1zG/YozOkBn+45klBC9S8a8n7wj9Pfz4KDnlnEApsZGRaGM/+cHf0FVHQ2t9zuRmxtZ22+Vwj3Qkyb35qrjQgkswV5afvRVvyUXoqvilLfXLoEmkkNbSzFcbfyXdPRVJbXJcE3yidj20b8cPjA/H6plHn0de89oS8ggihv0c3tyLGYAhCGvBBFYVUwVNGinJsB0je0+Qp2+GlR28yQyDmiiejX55t+pFWx4+Wnx70q2AvGfbItTSeI4Hxpm3lcExIg7AiWgqL0wfqwrIFqjkA1KtYRw1iXiHykBdrcxZkabHcsdgzkIgPwymoEpZxGGgxFdeqYVpH517jhDDkJljExsAZdj7P6cPTA0E1SWti+tnOos8TwcCyo1TAPBJIioRgTNTEdCmB8QY1lwqOgelFVjIWqJY7n/sM3C6KNbl+ppmLM4MRNyylhnk233WE2x6DbMfoQOVvQEOEyfZKgpCoyN5vbpUVVPq4YdG0C2W7BCa755WxYOqxLGo3zSKpGWkfFdxPOUu1FHbRqWtYcmuNZfAxCjRB49b9UubaTf9z8hLnbXRbclPjw0NGs9f5ow4s2zGAh5q8fSdYsl3YerZrXRVGTSaIJ8eI6udXjcvZ+vkXH3/H7av93xZoIKH/YD4FB4pqe+NLuIrcVql0g9gJvXppziEsOV5LmoYyDp6FJVFQI=
  template:
    metadata:
      name: redis-secret
      namespace: {{ .Values.appName }}-{{ .Values.environment }}
    type: Opaque
