# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: redis-sealed-secret
# spec:
#   encryptedData:
#     REDIS_PASS: {{ .Values.secret.redis_pass }}
#     # REDIS_PASS: AgBFcIykqCy1x6VtzkX/qYn/uLXW0sS/rMqPsygylELQ1f3PgrMxq9UbYN09roI1t0mm6MaFNa6/CSbgLbl+LvlikxebBO5l1sb779JlIxM/YxYgPKEQAk2tNdFUqe59jd36ThR5atxKhD9niNXkjLS/9C5Z2AtyisOcDJaOs15tRoIQxk9BuGpmT4RW2Ym0/Jid0X6EXLBwO8cd9U2MBCtbTnskGi6QU6LZiHBN0BOF9O6Y8wLIsFFNJvK7ZtsusNFYfBIV9HxvYvqsyCH3MDLv7vxNLqvUU59+sIIHnO+HhCkWr1Bpmf713SfVmQrGaiQN0Vew/gIV0GDXWpAL4O4M6G6e9Ucm7t4jAqsyw2e9/gpmJMzu6QruHyw/8mSzWYSUtZO22ZZ/DBQpkz9h4apMHmBpXqB773UdAgYSS19XvSbYp5BOSo3OWo7tN5ZsfY5hCzeNejuBfjev/EXTEcYTDT+RwOfyZ7wN3FA9XtsIQtsVH4zycPNTFcGzldl3H+9th2ipTq1G3VOjlwndmGj4S0sHDvLN+JTNxejkr82UYaV41v3P7lYDSTnCd+IirHgEJGiPjHelmXT546dP5hHkeyf6YZ3F/JGen/wyI8jYLbHOTTv3HQi6e2KAY1IVeQ3oQ5o1wqmL2g2vadrJtENy6PvV0lQ4lD9+jWbmHBbhnKGBzfHS9mYKe203Xk6yKML6MMDqh8mveHL4Hv4NlcpBKDdstVXV5HgIKiM=
#   template:
#     metadata:
#       name: redis-secret
#       namespace: {{ .Values.appName }}-{{ .Values.environment }}
#     type: Opaque
