environment: prod

deployment:
  image:  
    tag: 1
  replicas: 1
  labels:
    full-name: prueba-frontend-2-prod

configmap: 
  nginxConf: |-
      location /api {
          proxy_pass http://prueba-backend-prod-service:3000/;
      }
