environment: stage

deployment:
  image:  
    tag: 1
  replicas: 1
  labels:
    full-name: prueba-frontend-2-stage

configmap: 
  nginxConf: |-
      location /api {
          proxy_pass http://prueba-backend-stage-service:3000/;
      }
