environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgAFO9o/BUWTveZTj1yIfXKnwPMD6+r/aOQ7biR1MhweQ1kmKQbz5xk1qNM3K1eIjAv5ghAR4B4eBpp0osOdMkHxv2a4B9wcx1KBVFUyscwl+giyAtWBM3jWYGaNApKaTycLkp49Xh6eCrW5W0+VhtHnPuUl7LOWZ1pWk822Wa3wOLeY5oF6m1yq6OBDBrvA3xUQGbAYri5F8kW2gu+yqWx2UNOYYWCPa/7FmG8A711CX87IJpTLxQC2x82z0jYg0jfcl1fDrBaqGcH6NeUj6qRzttU5uQaRsngzqdwkMrYS+ojSyghG3wwxYJpR1MEQRwWQsDgTPj8MdZNeUs0KGcI5qlyIjh/qXn2F9M/lt9Yn4yxkKfOaW5QcZGbk635H+YjTbM4+WM1NwwpdVxzyW481YyAt43hK95DjFSz2NEVKrrlmNw5W6g+FNalu3/2N8zunR3rfdN9oLn1y5X+8IvjUcpuCcyZJmfrcIhHKENxqYe/wTlGrelwgNr9iXbYHf3K8v7UVT0N1SX0q2Xjen6UXiDjRWVkJkAVtEQ/UGXPT0E/3YUHIZ4Y1x9lbB5GfDTm2DBhUQVHS4t1R3X1UV16YswR+HAlUe9Fxh+sTHb7JfPYHmzm8WEkBGQmRK5y/TPLxm12StXP46wXbo+iV4gFwWmOUugfHm49mnRYimY1cBgiZNGK3QxpEC0WjVom3xxHagVvR9NrnVPLNFIJVNiUo6t3hMs7uCThbIXGQ # This value was modified by the sealed-secrets pipeline
