environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgCxY5uOJ+VX9hJ0y3cbldwv7l3ueOjAL3wplYJpmKOH/2voLMDz7xMFhMqMwRMGUu4keRUYwzKl8Ff69VFz5u+EK7UBGCyrmf7UsfLPLfsEbzYL66o6gBQ4q2nj2+h6qr6tbpDhRneRN7Y4OC3IGn7qad9Q+jAkZ5TxUGmvR81+x5bdHsK6M8fWzUbDwBoCECCLcAekbNtPG13NYdEL6atmcN0vS2WzSXss+ZVHR8QGUODdurFxY+vjOQ+HXk/7rqWH/wgat8bcCpy379bkXjVnSM9MRi1lIK2fRVqKmW6vX+RtPTMjZbQCKHRJ8J9NyIYPD0STbtv7h7QO5MtlVWg6iA2iib7+3L68EQTYjPWwu5j6DozdYOT09LDR6vefbNYwWLowb7fEyex54PQTEmlyupa9jL4sT60CqVCWNNneTP1xV5D8SCuEJX8SQt9lappRZoMCb2VCzjAsCqmyeozvAPj9MBS2g157QCQEnpwZY/eFsfC9yupwqmEwY9aspHkLe1/J5nFrPgAYiSLqWkWs6nf1bCGocCLleWPoS9h9umEp4q3loX0B8f5BDqj/67+lS6duyMhgZ0JwRiTP/956tAellxKtyHZ3c4NaHnGsGFsqGuqRHtLu+DQBxksjYNVQi3I9vUKyKaELTrNoF1KIhOj7KMnnDLizYG/nqLAV5cYUlXnLLT1vy124D+Rsln0= # This value was modified by the sealed-secrets pipeline