environment: prod

redis_host: master.meme-web-prod-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 1
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgBQ7ONBdunjaV9ygqtr8PMGkvrnu4xhjTVKMEyRA+F6W1zFvs1Pi/hdiV+8LupKacBJ0vMawOzhwscHMr3xlOA32/gj77Z+5baxkPMPqptnSmTbBM/W/qrRd8+osESbKvBmbjvMU6F4mwZfV76cySe1c7O9KTAjb+S6/G0U9uFWXucKjJQbBb1Qxt1DSK1ZkqE4uh8TBbZJ7uLZogpERISDr6dNR2BF9PxpZ6aj11Yv7afphZscqKbIpu7utMiBK2Ni0QoS75YddZo5d10XzNsEOC9yb39LvdqkTBDjR4Jqh2Qj82Y7CMTLXSMux36ZQ31e9vmyLuZEoFIfnXc/DrsSv1KDAJ1Bmz+M2j5Ubb1MAXe6RusBo7DdFsN65xaULkIXXolofmYFoRZTY+ZAUwOC+g1RvoWJpqf+4CuOjn/gkNrQvu4XwWyCzeoAvSPlFZsgfSObRb2VruRlym1cg+JrXAVwVlNqV3pNJNQGWrjol4iCrlGillcK6AW/tk6M1u7sKr/ThebhOna+JgEep6I1mQQc1Pw+Sqrnn4mVuaZn2sPnqhm3xBFbGEQ7aKhwwHJzxOhH7+sWkSxE8eeOTSdJjhj3p9p5X/hOJznLV3svmrBwEGdqPEu/yNZuYLaOkd7cvdFajDSehf5PK8EzHu6iIlyiOWGIEJDt7lsXOyKZ1vSBew4U2iMiXaSrC5ul4BQNdCRkIw5DdYsnVaQ70CgveT4HsYQiZyD0ICRZ # This value was modified by the sealed-secrets pipeline
