environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 7
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redisPass: AgB1lervgR9VMY9YjS4OgjEbE+lEPbhknY0uvuDNCqMoamqDrqxHC0D0XIuuBfLh/SCaI8cb5PP/kfnT1dN6B5LyNRSRLqU8XTu3qs+SOqGUSVmu+IFe1qb63OEB4zV6TglLxWXcKIjzQ+c5ua6LzD0r4FSLCGZ9/pCbOUvfOGjCNDPeKWQfA8LxCZHm5D+Q9s8dZn7MfwS3FckuJ0i8Nf6JxeBttOPsn5Hkl1e2tcBkKxEOKPwpI/5POjypPzhwQpKHjNV5xvOTOnWbvg9jf7PPwuQCh5cHBjJjlpyABnCoqSFh3qTseazaWkhl34ZUYUky2BP8QGU+8eh1y/NAHCS1lHRXa3V2Mh+Yhfnf1QAkciw649pLfpomNmixqzolcv4KtPhHPODvj9WkQorgNMYT3bDknah+NolCUYzDREUz07V+wEs2laVuLR9/59z5gHbMeZQU+lGkWouAVCxaacXcXyL3Wxzon/9TtJNXAKZ6dMd2dcR2fOw/BRDit/e3UIAtG9GyTd4PyuzEtucyG5vYkxHN0WDLWCB4VdsuQ3bfpzbTE49HWsjXo+3HMLfYWXzsRxsZhRDANKxH5kARSRfOlLUTH8wjeM0m+xmXBG/KF9Osd89O4v8oyjmKIxP1HOLyxrUg3YLXzMqjLcycnJh9uZ9AYys8Jq6UjkU1HTc1uOiKLXv5ha3GMbF2J28V1doQSv8ethwsK6vFDJ6TWTBMQBUSYp+ykM02WExD # This value was modified by the sealed-secrets pipeline
