environment: stage

# redis_host: master.meme-web-backend-stage-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 7
  replicas: 1
  labels:
    full-name: meme-web-backend-stage # This value was modified by the initial-setup python script

secret:
  redisPass: AgAwJZ5pIfJh5wH+QaS5sxIEwQm7lRLAenhjLiwEznXmXVS6yhQl3mrwWdMwlxBUnG1g8cwOnsRSErVuoYDuZx+waccwFFMK5/f+qpi2fxSb/4QFQ1YxozEN1DeSsEzBeVQmaPjPSZ/mTrAcrM3RO+oNgADp6o1v5DR051dLQlWsczspf0/bVsnjL6WkhbpPcQHeZ0UFX1KDVR7xZNhscHzXxgrjHdxEoFBQV/qrXRF2Dqd3orIz6Y15EJIuk97acUXpiIlyxCiw6aDCwgJDKYsQG4Viv0gYFrbViku94BEhOpcJnYGAzp9nf0kNdMV8e2EvnthCiSl4GJDVpp1U5z0gm21T8i4qdenRbBqmsze7PFxql/uanDShnymE+LizXllqLv6i0aq5VDwMToSy2TzPP4oUH4DE7D3sldRtY439zd1NwRnC3rKh4ZGO7maLimejSE3XHRAi41Zy+td+Ss7lkqeNxq9Tu+lr5isIZ+pUsWlR8/RfErIGH4OUU+95M03prLbDCMElt+RAMyzH24FVi2ySoJt27pCAQJhz2hMbbE8PQi1u1eTyZVMImCvvwo8ijcJEMaj9AIch452OPenZI4tdK58vQ4QM9vf7iqsRAr++FlSFyibkbdJTRlBTYPY0wub+LEwx8KF7LNCPk2/ogZexQRde46LAt47OTafSUd4E/7pjlDFib2VFM0EpOsKcCDb4viTCW0KGZXssjuy9NtVpBbCgvlqtaL60bw== # This value was modified by the sealed-secrets pipeline
