environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgCFPXLxOuO/Vm+4dkl/dTN379JBzSTLy4O8QXxCoAZfttwE5cGSuMb/LhWP32QId5Lc5i9Ay9bSnTWKRnN0YZbAvBM3dd74DEoMJz9k2fpOVJmMDWshiO4EBWnicuzf9szXeKWsbpGd1IsLaA4ayl+wG+AzrzF0PAQ8euk9SQh/EKyFWoIeDLgfRmT/yY4kNNJUhDt3664qeOtey+5IfwDkm/uUWnIZTQpQwc3D5CwogGwdIEIwUDagn8TQ08ltcAG/HEdxxvEiRLSEop/E9jY1uQiuSCGRUJcPIveOIBuVpZ+DTNjeC2HSp9jQxxR15toZ+VgZPWTvMGtyI41RK9QhN6aYTtiYCNG4X4sNeMUJIpXLMW7CVhCyeNj1ggidcepSF6deA243IZzwE/pTokIosEGlebtmiIWqE07PyQEkkCJMGgSRdPfvjKaMQRP4DiU/0kBTHEsV5idI5sEz19FwXhHrHpo7zKHc95cqUB97D8qO7giCaAUB49J0CAz1vxiZ44SZiRSHAbsFWVXIZitcL6c4wKlxEmoPQ3YnH8s/W2MlQNLsG6WWFkLpcKZY4iPI7HpT7ap6uT25n9MhlMM8p7fJdl4Du9VT+Zx47bDdp9Zlv732zJPNi+6/DmQdsIpxvVxjnxsezT8HiG/DaYhAYryBQEdxNLu24N68Gv/claVAq2T+OAgS1Bkg1vtbcEKrt0kZOpoD1DQU4OKM/4WxU5aeGtTmKcAOBfo= # This value was modified by the sealed-secrets pipeline