environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redisPass: AgCmBi5N/O+A1KCNzSkZVGR8BsBoamtImdC+oHwJsyFZFj0CnA+Lw9bxUpEUh5OmvAG6dzjesGqHOJ2MpsJJk9wvPoJ1DONmUUWHevURAnYuhRgqNntBBojpNE+qQYVyjCuqKzcFLa6egsfi3GTwX1iBo38As4eNm51VnXhjVpoqJdJYxY8+0H4/qJd7xT+7WL7WNDRb29LAfu1hn/3IgJf90hgkbaTs7fv3v0sAYeRAio8NQgB9SkbkNEXIMNBebHYQ7u70Ij1O6HuzN0OW+j7l7iET75ppCyLNQEstG5MEV+ggqiIKV/PdcgsjESq7HEBQW7XWNTIWQ7HOGyLJvo7gvscoC2SVc2sjyVFJdHGwCL6hnL8ZXSKQYoRlKvxAE1P2jFkqTV2jRUnTD3AeAdCsnOPaqV9nHi/Cjm6ETWVt2wO9ZFAVxQL5ao0dGDSnHvhCimqAnOzDIglsxJJn5+5HNKsbK3S3a5g3oK9omEM72Dskno9eS/bvCH0ahq8+ib+jVSalmSX8EqenttNZ770EHKFcEY+LsEIiymlhekJXjDiS2y06fT9Zc/oR52R9lypvmUkl3Q0Sd+m278t4ztdc6jgCD2H0g3Ka9a4NyEgf3RPADmAMjKsVf8lDOVt/j6mCF3TlZyZ21AQrZ3fwQNYqENg1daVOo5SrykJ2extt4Npj+1lbG2JaLgXgmMORXTM3GEiHb/fpia6tFiwqQOvlnIRPyaUwUztFo/q2 # This value was modified by the sealed-secrets pipeline
