environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgBCQnumvFDLcun0HhvmBOJc/bh7ZBGKPy4djiIYlvqarkW4L0TCiTGEBa5nQKgmq7H4+zf7KXb4hCySSagVrIBX/QmJKJCcimPwJiBtFmcpssvRAncyD14mYP+UIAt/rRUX64Y2IIBbiXCgCT/Gt3AGUTbWqhUbC/FtO+JgP+0fKMFqy1GXJptVSnDtue1p8jP554w070wkxI9w4anlfd8FnMxAYgEcVrHBRRVAQa1mDbeowS0zt4ld01BZQCjOAuj12OezolrEKYZQfYmNDD3gdA3fD/mB+P2h6QRpNdBDDf0IQgbzY1JpnnoGfmIzbzKPq/jQgVKRJ6xLUUeuRNCpLpbtTKBth1a/AJigW+6aTSTrfvMheVrwtkq6gph4FE755vfD+5F4hXIzwiGZxl7UwNxs1/eP6rbvKMGhurnwq0yAahdPrVbCprRGSMSevJrTOsXXeALsPDOvS2Z+Q6RDHxHn0N+519tfmGF1awBbqsQGNcr+ZryTch94/+h/AVTJDgHWREOjJEWQKbJw6ck89B6S/+nrSfV6YXGxxQLPuNZ+L3lnUGyhnT9MxmVVwP6nh4FgJEQ0/U3NsZucpCun19uNl+qQbSNSv7O5/CVCvpFbOaW7gp234Qv11jdfXYdcIWLsEeQCKcK2/9ZOTSUlUhv64rLIrKGkCn5QvgzWvVErywgSQO5v+Om7fuxCzEu28SWhJCe59nFDd6NFfev5ut6ZRkUu+q0Q3BSk # This value was modified by the sealed-secrets pipeline
