environment: stage

# redis_host: master.meme-web-backend-stage-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-stage # This value was modified by the initial-setup python script

secret:
  redisPass: AgCo1ugzY524RbHGb7sTTrKUI5653po90y1iflKANpWuVRf47VXYv+tJH49f+EVzrI1dODQYHzpHIH+QBIMjhRvS0iTnbxkB5Ey++Wka7PVTyJIYJyJxGsJuF5kAYtF0BYebA45RkD2TMOOq8QiqIKaEIwV2G0mCOM2BEsUDz/JgfgKGpCTc/siKKi0phk+0qusC103GC5D4l0QWix0CHATYbTVgmn3fgVZDoMH+zS6AIhYRY6CPisyGmVkULSjv/Ibvhdyxr3U1Di2QPs5uEwrkpq2e1r+4dOsxIcASTzcxaFL0ugnTkUuAcGGqc+M3t7sXkHVSb7Gwew89UJk/g3vg8foI+PUn5O9/0eIweSnxVnt/ZSTE/EhFXy/LqrYbMADUt5Xzua78/dBpRDGJFIcME8u8aCHkuc7dN2G1aIYMTFFSdfZGlvj8tBb17gF+a6enjKOHj4GOjjNLD9/wd2vnRiUtip9ZUd88vjmVBYEub/oV2pYyiPfYq5j7TV0Q11ZnfusvUJ4RiErQ3BfaQAKoYJocdOvlnRr0Kq+r+7oO1DQ5XYuVInyLX/NOcj/aOxULrsAb2FqdWz1wkyY+xrtAFl33TAKMIBzTXxZUizmOEZ5EhepkQCuKQ+c0KPT2KLXrgWnRSNtamDtys+ajSMH/rwEwTEZGH1zkOtGYKv+8hIhDMMiWX25RMbjIV0x2ve4= # This value was modified by the sealed-secrets pipeline
