environment: prod

redis_host: master.meme-web-prod-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgAAEfPFkEZFN7BKnYign+hGJ/+pyWi6tSzDpfPViHpShpZM64QH7tqW8hnDA7eBz8pkUolC2UtJV6qtsDcE0cXW63nExez+Ey/KB96goi1CbT/DVw+HE9d4/m5+f7Io0n3jeNz8SeEzc8/hWSBXm7SERJbC9q+J6i4WMkn4GIniPoS+6X9pR3zowMl5usg1gZ677+CCwsJE6wEnTeiiaBV0pTyyI5vOUVuHcT8bLqpjZWQdCTGtipHY4FRYZEVl0MTQRsBKDXfzyIxD/a247YYZi2UJj8ujkiYGeQZX5ysvAfw/HC8Qcuxbvg3SaR7zpu4YYpjNqWDZJllT415QQgOEaE0uHzCV2CFrySKKajxf2+XnpAqbq9xxUl9BH0Xbp3amLGn613+512Bvy40hZjWRXFhGU8o3j3eqSZPgO+h0+fnCTRxUhb1dhAF2rUfb5JKgYBDkQaJyVQqvGG/Yd5Q7fZnAU2ZC7gUwmRMqfMiRncC7uRdFmlXIf3jxlcPR8Y5YLuvBIgI1bsoDk0hEgMcQ8vnqrVVg2/cUEWuqwmA/rZHtxu3wru9EKGyg3ywjeBpTHNEFHJ3kAYT9xatzg8X27+7X83mQ/LjtOmOj+mplvoKMvVn0yCoIOS+0UENInrM0IOZJ6nwshLbTjBQaSwznHwoOMatLJ45p+5bZilSBxe2lD42FZHWQXjr12hgFYO5L1MXxLrEwveppEqL1rExD2e7ySeeCer55uezA # This value was modified by the sealed-secrets pipeline
