environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgBQnA0bD8jiLna2ZEZEmmwHnaTziGqO/CW395ODX6TdIzZEdx3rb9Iug814K8Ak5v3X0aBiFBOTH0J9QSKDKLrahZLNvEECBkODkGIlAzDZ6t943OgSPQ9egb8eMoICfG8MBN4fCb2GuKfqQTTsmnwCTKS2Jo82y781mukaqAZgP2Gmnc1rJzRD9PS9A9JFqlbJuKV3c7uOdKgm7WIoCBhofOEPCLCB3XB/wR3Y6w6BiR569e6pN2+vd4nWaukt+BuXGx/dTUJ5PkION3U5M79DXYJ7rzNmIFy4o1tJ/yiYxROZFV0lvEJ+g22dB1dS231PohvHmZdCOaI2ZdlkcKEiiqosN/N/XDV/nnNC3k9fPWZHp6gM57orX0hlQO1V9I+34Zmgbbpuvlrf1yglJLxYtRc8k0ApTJl1/yPv4ugiEB8tQz3vpQcErANZ4xz6nq4ouVexZQzKSDUMqsTZC1pVuc/bHXlWt1MFttw8yyC3GuMk7XjE/WnCSdh3uVEExwAlsxdpPQhm58IAVK/Cs7tswdJ5LF8DioEYOKy1YG7G51yeMQigaRIlEZLbGNDS0HBtWe5NBsk+T2IwKd4EtYZy1Z6sK6kz6J/yHvA4SXS67izcDTNGfIFpxOBBy9UPLp6ahUVhrhZKPDsuiMNLSb8dfs9Yg9bz7IFV5rL55DtQEmvX93qbDy07qKJ0rWuEDRnXXsDHEH1xmYQ0rPJlEluByCx+djGqOOwPF4o6 # This value was modified by the sealed-secrets pipeline
