environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redisPass: AgBMpdiarEeQ8mndeyCKZVLcLAguBsczqOCldC71PqArHn01OVJlbfB0iqmPZLH3pFLSjlYcsTJxuwf/VOb4g3aZp/8Ra1ovj7+4EcRLk2v5M9AliNr33DmHPq0I/qUM6aH7UjX9Kr5nEYW9TZt1DmkGt/sBGQ/5CJplD+TyUbFVdrdREX7mvNJSDRJtMMS/7YYuYBAf/a9JXzGi96Q82lnoHCsmhwwrdfyPwxBy74lTFbEY9NTIhGkGiipTtUeiZoxlHbgz0hWdBgCOBPtpNDZdgsk5+xrypiPn5LK2H0ajJDbfuSVfuoojpmsY8/GccE2kYFocYIMYvKB1hPNdYQhcfcVhTHZoEhJvdLs2zhZVIqaPC8ed5VhviUaXlPL52R+H80rMSf+9xYeHEpnSTvFa0zsWHntkO3pFob3Uy1iG6GwFLjsa3cvKCuIv0ug9QyJeAqSHdlnJDLYv2P1bvio+FhFmLCtKnT7kAAMtVGSyhc62atwkWbKCQVR/YR5EWnxcSaiO4sYHWcdXaayPtZwdCU4KaZoiDBxtw6ZfMTEp3fY42I4vzKS6uNojzlRz4/ZvWR9+A4ZvieIUJly7B96asgzSUhms99LdNfUjRJHs+xQRjZKpfTeRAFOWcLu92rycR7QyUK8tMEuj765TFlwbGD9I3p+RNs3gE777TSiK41hcdAG99j6IuU7zwBvuKZXGi5/Sc8u0tG9Uzys+bBiZP/KaaYwm5gm9dgm5 # This value was modified by the sealed-secrets pipeline
