environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redisPass: AgBe/g8RB0Cw6N5e5dMkxwWhD8YfSvkktiv93AbHmC/46CXk+7qvdL8pzMX0/u6VAB/nonpm1R1QXYaC9H06BJ7cyHxQMexUcSU1JPr3iW61dK/0wiWS2Tf3lt+Ng+Sf/41vWksZ8Y78JzPtViegf65BmFwsN2Usx+Mp9tkcXXnUDtHPb6KZ0PJepN0vMjx4jb+lT6y911x3pGdXVbxKZwnXpOX536WqPisBF3/1/vHuXNesgHOGq1YdGI5q5OPlERTXMEbGTplFMNSceWaBD6hhyDRfIdaTkUleaO+RepAxVciGmMovNL2bTPFiIbOh+Iz9FmFB7b/trWT0pI+Bw4wpWIaPZjEf/+7UvBQ0NK3kQPQUQua5F7uFt0v5Rb5od/zHVzf8ZopFgX8I3ANRPKbUUjs/giZcrr3yM02nL3hKW8PPpRgyWnODrmiIemvKORY8qZ37nysp9+p2QL0CsXEwZ7ksaXRRSKa3zW0smQ7wFFRigFSJKQ5ni9jt447h7hWQiTJwKY7oHrvabjglm/slc4lL4rQ1/HG4+qC/WmHA3C49Gn24D5jVH6GUVfFKoQt+ScHSx4P05H9vKpNP2Y7MbSTawu4F1mJfF2jvCbhood2+aC2U9E2wnHgQ//0Nxceey2YMs+ZJgc8EyQf5Vv7fDjZqhmTSDGqmKiJ4/yPiupy0AKYq8mXYmgdX36M5jGNq/6LXa5KRYxXzJ8NVB1bV/0jWugC6oj2VjTsB # This value was modified by the sealed-secrets pipeline
