environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 7
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgAbcZlaTSvTbdvM/5deN3j1o0JumrRL8G1Ko1qLsIrkwweXJtdvPO0JpyJ7tAMrzqoIm8YU8Z8W/cCDQ/V/C1lSOmRkSmC79mVlLprUBryqbvGGjM00DBX76CoSRPRqQ/nTEZ/P6vpkJXLYav0eCI+0Qoo3p20+XSS5e4V9mXmFK4dLJoRUw1KumFLbodKIBkfwkQgNNPNYBiH3bxV9FakUwjdyWLm/rMRM5nQ7Swjrncj+7Ln0gnBa+k3xDbKYXnStjQpBzvJ422lhNqL2T2ZLkzoUf1QKDVBRdGvX9KWXu9YkjgN6LAlm7XZqwnByP44ZYEMdMEh13MSQjjHmBYoxjBBj3ERmC58Ur3HsUAizHu+j1yRN25x65mQUjXV0bTGQ0cs2YLHlV4wo58OU01N54mOCZvq7YYOLR+lunMYXQpzgpVFl8yfbWA3adMHLmqVb2ixFzYb11CwL49RbDYkbn5lCPdjUdGqpDksIjv/qjry2LR4AV1hpI5hh70ztKp4GfigYsgDdlfmnkIqVVvqkE16fI3rFv6Q+Svy8ocDvH+MyNx1jM6VNA4hM9qT8COqkvdk5tZdpesz+XNcRuRCQHeWcl7e/bfpb8KtMQK4PEsIplyMhPa/1yjtQMgcjSCEclCDIyhuIVPeYc3VHNnbWY4VxsJlFPAEEZh+3rZ2LS8p6iisZ4rxZMd2TFp/f2V3OZKe5jhkEqgksnjna4E/yiZIX4HVgbNs/9sE= # This value was modified by the sealed-secrets pipeline