environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 7
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgAkvbUKD4IMxqBwAEAtlX5iOgnYsAt9DxG8n3WC4dhdwIKuCADqlzsfkgw7WmH5bdhtTTY7rtL5Yf6Y5vO9Bac3KOyufdLAOhY97R1dsFwwaicY6NlujWbNH2TqBH5v/AXubri+xdULGFaRa6guVAzqv9W0r/KKTm34j7a4PnSQcUnaTtjalc1JCnhCk/QBlOI5422htc9Rj+kqb25idCvaAzOu/vJwUXsEze8uCsLrDL0J8o1taL+EDLsljyUQQlAhTRzj9ybbXMGi3d86RCrel+ZKV6jGkf3Kb4a52qodIRNYJLtxxqBf8BzkP1zVTXdf4CIlZdczLub08dcKvQ9G9V0JEgXiMRHyQeojVwLDLffPGgPlxZHQUM9uuFHGcsxJ0celG9i8VI86WKbVWFHSe9c0hUqHE5ffnW3JC6AA4CAIKJWbRrRnN6VD7LgkS2BeMj9Nao4gZ6TPKe6FPnJszAVevLI2yj38gbGL/rUASStl0FU/Oynkm6Gl9TdDfwpgaXQrCP7Dcg7pvRhg30Sov+wGb28jZW/kOcum8W12nfGHL5oxkPv+A9Qg9wWKR7aNYqau51nkG7+rU1AVTYvFddv1Xq+RXP0uuO7MAlAn45N3GEUbVcgRcRGeHiOgmJxZ/ZVi+RmUIFfGjfRvmx30CZHUEkd5xOvHSdorgtKw6VUWC5wuI1vdG7uvz6pWOrQ95evmiNR6cWrwH9P4/a1eyA2OKKWC7TPaCbk= # This value was modified by the sealed-secrets pipeline