environment: stage

# redis_host: master.meme-web-backend-stage-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 7
  replicas: 1
  labels:
    full-name: meme-web-backend-stage # This value was modified by the initial-setup python script

secret:
  redisPass: AgCELLNtevRxKiTN/N/znQL39FE9WqDMAv4G1M4S3cgLvQaQCOolwgBU+WPoc7cfnp9OfSnZyF/eyX41a8XzrA9N1P+h7X8bWBqfQhDzHJ2QQabXRWC4WY+XWVKnYaOl4BI7WIRNT9WSq1BvUl60Rehm14ODZK1dGGlRtdac+92mpNVsZAFd8pFCikF6SExEwja6TBS3fbQ0RhYPR4PPZw7X/ljPPRZ1tymsVK9tYajE2yxRLexh1mzpw/8ynGaAZopjpB7NHdwkyeo4GePHLbebeez0wkRSikuQ3rdipX37f4/rjUS9dHUml78/7DdW7vYXFU/9iXNEqhlhndWmnFBCcT5VIP35DR8/VLcZZgknyfmJ423l5aHht/PbCtWcAyz0Drhvn1M40lHPh+xnNnvqrgIYwFNHav62HnjJ87Ojlr0/V7F/gVxdO4aAaTc3F/TaoLqSQy41NXgico4PhFYKcvE8w6nqM5i9UBc9/9P2wFELTDONPFVUbzXehGXf+OgPKFuxgQtB6k1GveCFlB89oN6375ph8lv0iISS46b6O9uoNjDRQegpk6sG7T3M5BeSYelmJMma3CxiWnzep+x2QoOlvJQwJdifScehyXTj16We6VuFTX6dLJQ1lRP7vL43PRl/Dx0Z+WnflIANKgDTZAvPRO9wok1+prYyyVylYaLEKiJKEg/1LoVM+B8AxVBFTKt1O9B7Q/b7wOb3CP+VH0hhWhz8hI+r3eu3Yg== # This value was modified by the sealed-secrets pipeline
