environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgBMkiaG5uIIXWDETGbHt+1wxNtzwLYrz+M30ENPzs6sESS0I025usVnedxFCVVnCbcLs+wwlAhvtMnPXyBp48WExVyESq1a3i3f5dI/Rup8XKLvv6qd+/hk04UYqswtM/M37mTje3DH1IbeNQgGKtZ7HbW/Qu0Le39hFdjXWcTGhKE6IQ7t8ykbXeSG2wiLuJTvpqFHLxmP9PbDxk/pdHRm0eiWFvOKQqK7gNzTuPjukZwKB6FlMvR0DqZa1Df4lfV5v+zGho+J3X4sMxEtcl9j9sn8D5WGyxeRPJ+MV03fH3f8O7nSx18r5LIZD3xQSxZzHqkueQP4th91k2ayh/zAzOeIBxNGUmD84M4OSe0n8yibWbLhiArAEvOo5OXMWBeHKq4/77gy/e5ansj7DhrygFgSZa7vSOA5XPRsvQ4eYGHS9CyX8qGHqpeGVCiCNdH+rn5yrYCO0wzuxG5RvOcp0CspHV8ADmhDyW2CE/T7aVZWB3DvutJSaVMxwDdCvQLE+S7HPfUlsN3GHmNafQ8A18jtn1Ua+WY4jN4cU0pZjvRsV5XYfmGgkcZ7NGuQLu4lbqRMawsjO2QoX7oJCxPOZkPP2O0Ezmiz0fZTFU3GNmyaRP0RW15alQdH25Ac9sDdM6eIlRh3UnTMsfOBPoAgIUO8MG70IKzBvCK8QdvGnGdxS5i+Zc1OphHAEQ7evLLQgzMlrmRpqK2cyuFCV8w5RtqzrBeHmyMdZKM= # This value was modified by the sealed-secrets pipeline