environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 11
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redisPass: AgAJFDFD4iQb3XVSvcPvNYjIz9+uNbnFex4q2E7rGkOKrseThJpA3SFwD+aU1j2xQStV2ZntTyYwSmVmfO1GVhsJq/qt8oxJxkuw8hKW7RRenbZiMi0AzGyH/QVwQ01xvO0orzKvwUwCaQnJhuFBWYULSocwH+KdZ32yTBiPMUNsaSgj4lfP8XbZzegOe3PzsL/bUIGa/NM+bQEeQ03DswTk8KYke5lsigo7o1tsJs9wz5wMU31/0VxcjpnzsY8GJRaYV/gC5e4/fmvmiCb1BtagIZPgR7IvbwYKWDhWgpD54gaIyA0sDsJFJhmUA8fMxHbZBREWKVaQ34T/C7YP5+/dx4vHpBjjG/MBT9xstAOk1+rRasuUJPIVAHK8IPWD5eck5sF5HymDcLvV889QsFInxsd51liQefzEMLP7g2V6wIiYlp4kZzRup6wz8DBvf6AUl0c9bWWa0W1XG/FLFyzJuokCtqU+Bvwhkx3V2wk8RZF46sHMdrTlVDRlQO3VD1HpLt+bQvsjtmnZscKiH2jdEU5byEsP6XQDTGiE6oVAKnGXfcsh5aM3cJ4Gtsz4mhsPWopFqAeQWqHpO6zGgBeL2QCfDKt/W4B0xHWhQsYSE9llxpTjgDsCZ4oO8E8yo+PlShYALnaRP5elTOn5V9K1OyVdWj/hnLDUqyYr3yuJwKXLy9huc60HFSGCUis14zA= # This value was modified by the sealed-secrets pipeline
