environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgBC3OtFItA4cSZhJlHUf/Yi29aPB9Fyz38lpNimjCn8vMsR63R+xACy3A6FBmZDaUlBuyyoLxZRB7+HkmzA+tKrY/xcJYH2/1//N62nRicZ6/CALvP00UcXkagEyO/aGsZBXIQAmfd80mX94ypwFASqObPk78ohd6669Gu5eyB5i85joKR65diirIatjIMnPm6pKh7NbT37p/1KUhMCUpxapeYKDwAi0hoVvE6qec//8J/M+JpYd7g3JzhbCQluG1oCmvxp5j65wlM4molg44k9pYMLjyhwNzBsbOwUdVs51c3X4mo1Kf7Eoqb1563wnXcgPIWwGnAa3fe7FEaJMejvFXowmlQGAEhEv4KN+ztMWexPEKPF3ThN/LHwqg6AP+KXBMWLGoZYTElXcuUDRbJxVVbkh9E/ugCGL8uTOtFZONiWJgGSN4Z3f0MlG/k5y9A1C/Rc8K4WcduP+0H36Vtbq2oWFrukWUipmWwZr+vQkI4VjderSQsBqwnaAmjuxM0sHMtxpZy25VRDzghBlkZwhESMg7z0bX7KUtZCKxvtFVmbx7I09sVnzSlmI8sbmawEH88HrIOX8nEixMS/XJ+myQQWpYJtO36mezSORMg6I5iAjNYTAlVX3rfmFyeRHoADxcX0yuKR/U6JWBc3O3CHBRZixx6VyLXGcsNBAPfg2lUHkaVoCuxJP/u7OSRVsfNPHO8j1vWNm5C7C8SmVEnHfj5J+iTg1Bft+Mmg # This value was modified by the sealed-secrets pipeline
