environment: prod

redis_host: master.meme-web-prod-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 1
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgAMzt0P1w3UirNlNvl2i94HSjC0LEbari84p7KDebJprmJ0UtIMHuy1zxN2mo/SHnaLnjS+VJbk4R3p+MQQdzkazeE8aBmu0pcNau/zqo8UqhbGxnfDy6uopSw5GHbTHHGPn2jlDWi6np4U8o9aIdivj2TVcLc/GKxGiOx81N3L2UhACE47VOL4W5KpHVkXYDqQgvh+alh2KVelhWPyGUMiC7KgalAXN5YTr1TYPuE9W8jkp188I0Gm0bM6f3eSHVa4vFPNaV1U1U2m5vjWV3rngzdqH+3mLKhcqh/TiV64G7LBt5EB762ERpbIHwh1OoHCB2mAbqw/GmLqf+on86N5wL2bs4GkWkZ25CObPB8bDYJg+QU8kInRK0cCcLyFc8XRUbLzHITh7yOL0QuglM+PcuzCtRnI+p8LfQch9DyDsjniGhvGIul6Osfm2FVAleNeitdeB2GY4x71O7dmTqxXgCziazQgF4GMzRZEj848nXSb9/r98ofsPiV+q8Q/2ws8NaHtjGEjPKUMZZM8rJlqI+P6ZzXa2iJdBtRGdQd5JPv46N0ii0VJvOWRVziyiOcFfLNQd/TZQn4O4ySj/nZK135aQLgGHtnk9b1wOV3l6ydb0K/jRq9oOdGI/uKnESJWI9Jc1L5dirCYb5JJB/zx0M55aR0YAgBsgUKRNgWOFRlO8qlDM0YgsY2/HipCHWDTIpjMVvuhbT7zrKuL++WmycwgQkQvCgkhQotx # This value was modified by the sealed-secrets pipeline
