environment: prod

# redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redisPass: AgDfBp/ZtSWDsG7OwMTbrTo4TkFQTxiuGn97QPvjStC0dHxeod4tRsegezyQqOsHFImpfwVHaBMIYAwPt/SBeHkjYrNKP/OmtiEpLGpm1kalsohFlN1s43bDhfi69jcUfkLhyUgIqP0TivzKY4PDYheK+NwRo1Grp0OWR78zAZ4HAMLXOrtS+EnclX5i/oRkEPgxc6rcaTh83Q+ZvMQ/OAj+e40twQtESuP9XKDQtc8Zjrzfd1yT+faATHa82vpixLdV1wBKCkFC21QIdped1Vo2RAQU5EIb349NVJ0UJK6mF4ubfBJI9qwNpifE3GO+uFBwcSBKe/hOxAyLWm7/G3qCdus2XdTLB/bKmgGapdV0VsJg9mL/hlRY4JrWyb5LAPb5uwmX9h8LYh4B12OQTghE4W4rD1xjGHgneXIDGDKN46J+VGZ5NV8ttrvca7TbTE98xqwd0QqjMzhfBjP5wj3fuW10I5hft3X87TUjdhxtW7XGTxSydqOhGgQ08Sybag5lfdmEIhYV4uLrq7dWPjugU2UnzfNtamr1M+W5FpiqCYue/dI5QTRdyRkgTelOKxuppmczEAX+/c2vgDXU86c4Je3gmoxNWMUoiJDVMV2P9M2z4DLpYoJ5UAJBgbW00oFUGVBpmF6oXKZbtXDf9MqTSaVZsogsfvXv3dzw4nMICLKKHdZLYUA6NOmLHTUywRMEMXnqK4ofIn4JbCAoAS45WMhgxtvlAQNNDTGL # This value was modified by the sealed-secrets pipeline
