environment: prod

redis_host: master.meme-web-prod-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 1
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass:
