environment: prod

redis_host: master.meme-web-prod-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgBTOSDdRTB/HwDyJxL9R7e6EwIbsK2ABAislMn5fUzZAQwRxhMWxVTVwphqSR6FeuGVdHSK+Ib0q0xoG4ZLxwW312I+1ZN/H+7OHUVHNve0Hymt86P0DWt4F0WkLlNPRZTbTSBimhEseXHCxjjogVqK9eBhfqBiYJh/0+rttB59QwuzRMLrC29CZhPr3SyOpkMLQweVdCsouhTLdlkktoS1F5kk7BXGIMUrC4UvYHJn9IxEl4bn25Wh6sUeh/F+yE+9wS+4r1lLkiAhjflbHrle9qnn/vh/IeQSPItaKnpp6GGNMk8AtBldwrRC0Qyp9VIuhI3E79AxO9ywNeTkYIdZHe89xtZps2OvRnziyx9BhMsKkUNDMXplISdLzjY2BV3eVaUTqTuDiZtX0dN2yKltQksjdfZQPArKnSLNKlQ8rlSfNFjdYPkjDRiI4QKj27jGFbVfZWnz115iPJJjyob8ZoHvbCzwwb2Uw1jTM5UXN28BRLICxmjEVTqHWYlNiDB3jL4dxxX/U/3mjHVx5ZsbeeylaeVcZIN8FCpmZGpG67TJu84pgDkvJPu2p+hsBlLjMlyKiXuL5gEq5HmVRqbDsGXESLr2eIHBJrLHF4LfbLXQLRYEPYDIMtyEHgmxKrVMGtUDTe04poQGofQRMF14dQVGkTsziqFmoaTeG/xp/NASQrTmwW+7UETifMM6eLS4mKTWIXen+8yVJTl3EI1jxwjyzjyr+mTrUywN # This value was modified by the sealed-secrets pipeline
