environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgAkzWwj8tXj33TgNJ5vFUkNsLy1X6QcQvH0+rPVx8jGtZREDTABa7W0kMxnqYyeOns2b+zrKe3nW6ZgKvdUZx7ntHGW3kVmOIv+Tv/lKmEfdn6toaddSyXg4DeyKIjOl6+i77/KSjvT8/qKWKhrHcfj6kvz2NVi4pzGgBS/IucFWug70VkCfpEzRR1YMujt7RMa3sWmw8GFqOtI9UetDY7XdMSWhodoCf1pOK0CMPxjTnkiwgwklDyYBoDRIzMMrRQjRz+MFIqCfPEOAs7YjTKFvDEbQtc9p2f+mkaWf8tqVxHlWF/SD3okAr8VQBHfYKdW7BbZdkEddW+Q2PJxGxle5XksXfX/QEOna0YS/r5vMLeOL3PGfYNTAOG+KMs52mDqi674cLLgOlUfDoVsOEo2bWUYfzzRBEhg6J0gXgmCFDHW7IG/eg02TxeQoX7fexdvVUTNqWJpCQTimoJoFC4oA+4Ka6Xt+o0elxFsoScFrWkjZPtpZEVQXpmG9umxtqIH5olg+BpsrgjFSc0ffhGSn7C3xpFXv17jpSZomOvS/HF05yqaKERI/82Yqv8RYFdZGWnn1wfwEwEf+23EWwZ0CyuhlMtzpHM2ZNYegfvTPmHz2HZTebZeM1kBKqSDpeev0bYRX7vvHxYqEsYuZOy7p9bsU9kkjf/8w/QdkpQ/ZYsl0kdy9pByXYEvVVsYNoA= # This value was modified by the sealed-secrets pipeline