environment: prod

redis_host: master.meme-web-backend-prod-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 3
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgCoXEVl2YMjxJpJuq6OpSR6dEQY0Ret/89Ww9x7B7E9GJXCK0znfzWp4IL6xHXoEzBYg6iSBh98MhLG9N1+I9E9/drIWzYr6WhrcTWgUhOY0BcvKEq7eL8VQkA3y/iXIs5AMl4KWLgIhtxr/JZ4cDrUxTrNxwfsfaIrlyb2FXupkb46c7ATkK8dBkOLaEgSQYi0vBM7bXuYr9grgTXWtzjiB//wPNQBIvtOGXIJAJWNOs5SaxSHSz6XoKFPEZOPIfnUDpL6cc3EBY1lF5UCgMqX/ja0wx62gXUxhRnw8HXzhKL4xqAZ2HenOGhE8TWe4lzpDLrQUy8lpWDfOXhNr4vS+jC5piSh8JMeH+NDeipwX6+zgOXzj7JKkJ+C8poVqRNML8Ky34qsktTOk0H5k3K1D3exFDQQ5TYjlWXkgIO0k97O13hLzSzy+AhEkajGFEVIGmyy8Ms5fmt9a+fjIAG6fvZ5wzvMrFzFyO2fKOrgYEPGSmqNZH1E78ibezjShCH7XnqyjVFXruq2909fsVo0KgrLU2OTCQ/m9bJe3dza2bGrUqO2cY1oIV5iGjek1Yk6pa22pXfFUdv32udoRPX7+eGElQwL8BiZgRuhtdQT/bZwG1F7sx8dO2VzCJHig5pyTcY5ntNVMOQ6m+4/W+xb+4B6Q5eo3QljIf44K5Oyd6gotnc/NvhXIFaPK4WyfWhvTC3+TJJoNpYs9qOizmKNoWXHaM4zpOSyJZaJ # This value was modified by the sealed-secrets pipeline
