apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroup
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-elascache-rep-group
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    meta.upbound.io/example-id: elasticache/v1beta1/replicationgroup
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    automaticFailoverEnabled: true
    description: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-elascache-rep-group
    engineVersion: "7.1"
    cacheNodeType: cache.t4g.micro
    numCacheClusters: 1
    parameterGroupName: default.redis7
    port: 6379
    region: us-east-1
    # securityGroupIdRefs: 
    #   name:
    # transitEncryptionEnabled: true
    # authTokenSecretRef:
    #   namespace: 
    #   name: # Name of the secret
    #   key:


    # replicationGroupID: "{{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-elascache-rep-group"
    # replicationGroupDescription: "Redis cluster for {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}"
    # snapshotRetentionLimit: 5
    # snapshotWindow: "00:00-05:00"
    # subnetGroupName: elasticache-subnet-group
    # securityGroupIDs:
    #   - <security-group-id>
    # transitEncryptionEnabled: true
    # authToken: "automate-all-the-things-{{ .Values.environment }}"
    # clusterMode:
    #   replicasPerNodeGroup: 1
    # engine: "redis"
  providerConfigRef:
    name: default
