apiVersion: elasticache.aws.upbound.io/v1beta1
kind: ReplicationGroup
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-elascache-rep-group
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  #   meta.upbound.io/example-id: elasticache/v1beta1/replicationgroup
  #   uptest.upbound.io/timeout: "3600"
  # labels:
  #   testing.upbound.io/example-name: example
spec:
  forProvider:
    automaticFailoverEnabled: true
    description: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-elascache-rep-group
    engineVersion: "7.1"
    nodeType: cache.t4g.micro
    numCacheClusters: 2
    # parameterGroupName: default.redis7
    region: us-east-1
    securityGroupIds: 
      - {{ .Values.securityGroupId }}
    # securityGroupIdRefs: 
    #   name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-databases-security-group
    subnetGroupNameRef: # esto es para referancia a otro managed resource de crossplane donde entrara la infro requerida
      name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-elasticache-subnet-group
    transitEncryptionEnabled: true
    authTokenSecretRef:
      namespace: {{ .Values.system }}-{{ .Values.environment }}
      # name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-secret # Name of the secret
      name: redis-secret # Name of the secret
      key: REDIS_PASS


    # replicationGroupID: "{{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-elascache-rep-group"
    # replicationGroupDescription: "Redis cluster for {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}"
    # snapshotRetentionLimit: 5
    # snapshotWindow: "00:00-05:00"
    # subnetGroupName: elasticache-subnet-group
    # securityGroupIDs:
    #   - <security-group-id>
    # transitEncryptionEnabled: true
    # authToken: "automate-all-the-things-{{ .Values.environment }}"
    # clusterMode:
    #   replicasPerNodeGroup: 1
    # engine: "redis"
  providerConfigRef:
    name: default
