apiVersion: cache.aws.crossplane.io/v1beta1
kind: SubnetGroup
metadata:
  name: elasticache-subnet-group
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  forProvider:
    name: elasticache-subnet-group
    subnetIDs:
      - <private-subnet-c-id>
  providerConfigRef:
    name: aws-provider
