apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-databases-security-group
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  forProvider:
    description: Allow TLS inbound traffic
    groupName: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-databases-security-group
    region: us-east-1
    vpcId: {{ .Values.vpcId }}

    # ----------------------------------------------------------    
    ingress:
        description: Allow SSH from EC2 instance
        cidrBlocks:
          - 10.0.128.0/19"  # CIDR block for public subnet C
        protocol: tcp
        fromPort: 22
        toPort: 22
    # ----------------------------------------------------------    
    ingress:
        description: Allow redis-cli from EC2 instance
        cidrBlocks:
          - 10.0.128.0/19"  # CIDR block for public subnet C
        protocol: "-1"
        fromPort: 6379
        toPort: 6379
    # ----------------------------------------------------------    
    ingress:
        description: Allow EKS nodes to connect to the DB
        cidrBlocks:
          - "10.0.32.0/19"  # CIDR block for private subnet A
          - "10.0.96.0/19"  # CIDR block for private subnet B
        protocol: "-1"
        fromPort: 6379
        toPort: 6379
  providerConfigRef:
    name: default
