apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-databases-security-group
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  forProvider:
    description: Security group for {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-database
    groupName: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-databases-security-group
    region: us-east-1
    vpcId: {{ .Values.vpcId }}
    ingress:
      - fromPort: 22
        ipProtocol: tcp
        ipRanges:
        - cidrIp: 10.0.128.0/19  # CIDR block for public subnet C
          description: Allow SSH from EC2 instance
        toPort: 22

      # - fromPort: 443
      #   ipProtocol: tcp
      #   ipRanges:
      #     - cidrIp: 0.0.0.0/0
      #   toPort: 443

      - ipRanges:
        - description: Allow redis-cli from EC2 instance
          cidrIp: 10.0.128.0/19  # CIDR block for public subnet C
        ipProtocol: tcp
        fromPort: 6379
        toPort: 6379
      - ipRanges:
        - description: Allow EKS nodes to connect to the DB
          cidrIp: 10.0.32.0/19  # CIDR block for private subnet A
        - description: Allow EKS nodes to connect to the DB
          cidrIp: 10.0.96.0/19  # CIDR block for private subnet B
        ipProtocol: tcp
        fromPort: 6379
        toPort: 6379
  providerConfigRef:
    name: default
