environment: dev
    
deployment:
  image:  
    tag: 2
  replicas: 1
  labels:
    full-name: taylor-frontend-dev

configmap: 
  nginxConf: |-
      location /api {
          proxy_pass http://taylor-backend-dev-service:3000/;
      }
